### ISSUE TITLE
Performance optimization frame time charts

### ISSUE THREAD

**Issue by DevTechProfile** [CXWorld/CapFrameX#106]
Data collecting should be reworked. Using less .ToList().

**Comment by xcasxcursex** [comment]
Was this the result of the profiling from https://github.com/DevTechProfile/CapFrameX/issues/96 ?

**Comment by Taxxor90** [comment]
Updated OxyPlot to use new EdgeRenderingMode greatly improved graph performance

**Comment by xcasxcursex** [comment]
Thanks for sharing I've got a few projects coming up that can really use that knowledge! Thanks heaps!
