### ISSUE TITLE
Problems with refresh rate when G-SYNC is active

### ISSUE THREAD

**Issue by DevTechProfile** [CXWorld/CapFrameX#115]
CX window lags on some systems when G-SYNC is active. Workaround by defining a custom profile for CX with G-SYNC off.  

Cause: G-SYNC is active for window and fullscreen mode.

**Comment by DevTechProfile** [comment]
Workaround works for G-SYNC Compatible as well.

**Comment by RodroG-85** [comment]
I noticed it time ago, perhap I should have reported it... I use same workaround and fixed it with a custom profile setting Fixed Refresh Rate as the Monitor Technology in this case.  The issue it's not exclusive of CX it happens also with other apps when G-SYNC is enabled for fullscreen and window, like Superposition benchmark or even Steam is affected.
