### ISSUE TITLE
hyper space

### ISSUE THREAD

**Issue by kyrox02** [CXWorld/CapFrameX#126]
hyper space dont like capframex its close automatically

**Comment by Taxxor90** [comment]
Need more information^^

What is "Hyper Space" ? A game or a software?

What closes? Hyper Space oder CapFrameX?

**Comment by awinnen** [comment]
Hi, We received your mail. We wil try to reproduce the issue.

**Comment by Taxxor90** [comment]
Aaah, Hyper Scape, not Hyper Space^^


Well, I couldn't reproduce the issue, which version are you using?

I've tested 1.5.2 and 1.5.1, both once with the Uplay overlay enabled and one disabled. Nothing closes and captures are working fine.
![hyperscape](https://user-images.githubusercontent.com/45570250/86511784-8fc9d980-bdfc-11ea-998a-dbeb9e87febe.png)

**Comment by kyrox02** [comment]
im using cx 1.5.2 and windows 1709 10 its not working for me its close auto

**Comment by Taxxor90** [comment]
please try this version
https://nexus.cluster.the.mind-blowing.dev/repository/CapFrameX/develop__feature__new_overlay_options/04.07.2020/1fe92374444f7e2fac8a972d4ada4879120d4cd9.zip

while I wouldn't assume that it will ix the issue, it will give you a better log file in documents/capframex/logs that you could send us to see the exact error that causes CX to crash.

**Comment by kyrox02** [comment]
[CapFrameX.log](https://github.com/CXWorld/CapFrameX/files/4872943/CapFrameX.log)

thats what i got every game work fine only this game close auto if i try open in middle game the capframex dont detect the game

**Comment by Taxxor90** [comment]
Just to clarity, what closes? CX or the game?

**Comment by kyrox02** [comment]
CX

**Comment by Taxxor90** [comment]
So when the game is running and you start CX, it doesnt close but also doesn't detect the game?
And when CX is already running and you start the game, CX closes?

And this log was made from two times starting the game with CX already open?

**Comment by kyrox02** [comment]
yes

**Comment by DevTechProfile** [comment]
I cannot reproduce the error here on my system. @kyrox02 You should update your windows.

**Comment by Taxxor90** [comment]
okay next try^^
From your description it would have to be a PresentMon related problem, so we implemented some new logging points.

https://nexus.cluster.the.mind-blowing.dev/repository/CapFrameX/develop__feature__new_overlay_options/04.07.2020/4314e0cccf4a8e761518d0860d58d39af88b8b0e.zip

does the log state something different this time?

**Comment by kyrox02** [comment]
yes
[CapFrameX_003.log](https://github.com/CXWorld/CapFrameX/files/4873014/CapFrameX_003.log)

but its still close for me

**Comment by kyrox02** [comment]
> I cannot reproduce the error here on my system. @kyrox02 You should update your windows.

i dont need update my windows cause every game i try work fine only this game its close  every system is different and if u cant fix it its something that u cant deal with it and give up

**Comment by DevTechProfile** [comment]
Your windows is from April 7, 2017. You should definitely make an update.

But I think this problem is very special. I'm afraid there's nothing we can do.

**Comment by Taxxor90** [comment]
It may very well be that there is some kind of problem between Hyperscape and PresentMon that only occurs with older windows versions, but none of us has a version this old.

You could try if OCAT is able to capture it on your system, since it is also using PresentMon

**Comment by Taxxor90** [comment]
Another try to stop CX from crashing and eventually get some useful information in the log.

https://nexus.cluster.the.mind-blowing.dev/repository/CapFrameX/develop__feature__new_overlay_options/04.07.2020/c0519a28d5c56cf4e91d0665e085ef7ad5e6df75.zip

**Comment by kyrox02** [comment]
> Another try to stop CX from crashing and eventually get some useful information in the log(though it still shouldn't recognize the process).
> 
> https://nexus.cluster.the.mind-blowing.dev/repository/CapFrameX/develop__feature__new_overlay_options/04.07.2020/c0519a28d5c56cf4e91d0665e085ef7ad5e6df75.zip

thank u so much for that hard work but thats okay i will use msi afterburner for this game cause this is my only option to capture 0.1 low fps
