### ISSUE TITLE
Overlay doesn't show when profiling Google Chrome

### ISSUE THREAD

**Issue by whiteboxsolutions** [CXWorld/CapFrameX#127]
Current Behaviour: When attempting to profile a Google Chrome tab, the overlay does not appear.

Expected Behaviour: When profiling a Google Chrome tab, the overlay should be visible

Steps to Reproduce: Move Chrome from Ignore list into Running Processes. Activate Chrome and hit Start Capture hotkey.

**Comment by Taxxor90** [comment]
CX has nothing to do with the overlay being displayed or not, it's there wether you ignore the process or not.
All we do is push our info to RTSS.

If RTSS decides to not show in chrome, you'd have to take a look at the RTSS Settings to see if you can make it show there.
