### ISSUE TITLE
Captures not saved - No indication of why?

### ISSUE THREAD

**Issue by talbotmcinnis** [CXWorld/CapFrameX#128]
I found this amazing gem and used it on one machine without any issues.  I just tried on a second machine, and after I end a capture it says "Creating capture file", but no files appears in the observed directory.  I don't even see file activity using procmon to see it attempting to write anything.

Is there a capFrameX log file I can use to help figure this one out?

Also should mention that once I attempt a capture, "capture service" goes back to "Ready", but I cannot start another capture after wards.  Triggering the hotkey appears to do nothing at all :(

**Comment by DevTechProfile** [comment]
Which version do you use? We've fixed this issue. Try 1.5.3 beta: https://github.com/CXWorld/CapFrameX/releases/tag/v1.5.3beta

**Comment by Taxxor90** [comment]
> Also should mention that once I attempt a capture, "capture service" goes back to "Ready", but I cannot start another capture after wards. Triggering the hotkey appears to do nothing at all :(

Yep, that's exactly the issue we fixed with 1.5.3 as you can see under bug fixes ^^

**Comment by talbotmcinnis** [comment]
Awesome answers.  Thanks team!
