### ISSUE TITLE
Video Memory Usage is missing.

### ISSUE THREAD

**Issue by HEisUSdot2dot0** [CXWorld/CapFrameX#130]
Video memory usage is missing. I've found that it's missing when I was comparing to MSI AB overlay. I was searching for it, but I haven't found it.
![CapframexVidMemMissing1](https://user-images.githubusercontent.com/54422599/88844618-970db880-d1eb-11ea-93a7-829878c6a4c9.jpg)

**Comment by Taxxor90** [comment]
We're very aware of this^^
We currently don't have any way to get the VRAM for AMD cards, the sensor libs we're using don't include it and there are only a few tools that can actually read it out and those are not open source so it could take a while to get this.
