### ISSUE TITLE
Certain sensors are missing/bugged out

### ISSUE THREAD

**Issue by siegmour** [CXWorld/CapFrameX#131]
There are certain sensors in the overlay menu (listed below) which when activated display only "0C"

- GPU Memory
- GPU VRM Core
- GPU VRM Memory
- GPU Hot Spot

Furthermore, there are some sensors which are not being picked up by any other hardware monitoring application (nor should they, since they are not applicable to my GPU):

- GPU Liquid
- GPU PLX

Thank you!

**Comment by DevTechProfile** [comment]
Which graphic card do you use? Did you try the reset button?

**Comment by siegmour** [comment]
Sorry I forgot this crucial info -- AMD Vega 64 with the latest Adrenalin 20.8.1 drivers, Windows 10 1909 build 18363.959. I do confirm that other monitoring software (HWInfo, GPU-Z) does detect and display all 5 temp sensors correctly.

**Comment by DevTechProfile** [comment]
We've fixed it. Here's a beta: https://nexus.cluster.the.mind-blowing.dev/service/rest/repository/browse/CapFrameX/release__1.5.4/18.08.2020/
