### ISSUE TITLE
3950x many overlay items duplicated or incorrect shown

### ISSUE THREAD

**Issue by Kyouki-DotExe** [CXWorld/CapFrameX#132]
Prior on the older version I didn't have this issue and seem to have started since the BETA of 1.5.3. Not sure how to resolve this other then delete my old folder and use a older version of the CapFrameX overlay settings file.

This is roughly what it looks like on the new version with no overlay file yet.
![capframex](https://user-images.githubusercontent.com/70185861/91117712-90aa1980-e68f-11ea-9b0f-787d492a595f.JPG)

If I import my older one I get proper overlay and then it looks like this:
![2capframex](https://user-images.githubusercontent.com/70185861/91117773-bdf6c780-e68f-11ea-97ba-377e1dd240c0.JPG)

**Comment by DevTechProfile** [comment]
Try to use the reset button on the overlay page.

**Comment by Kyouki-DotExe** [comment]
That doesn't do anything for me, I have tried that as one of the first solutions to the problem but it only happens on a fresh install and without my backupped json settings file.

**Comment by DevTechProfile** [comment]
Please try this beta: https://nexus.cluster.the.mind-blowing.dev/service/rest/repository/browse/CapFrameX/release__1.5.4/27.08.2020/

It gives us more logging infos. Remove the old log files under MyDocuments\CapFrameX\Logs first than install the beta and give us the new log file please. 

Just for info. I have a 3950X too. No such problems from my side...

**Comment by Kyouki-DotExe** [comment]
Hi there, I have removed the old version, removed the CapFrameX folder found in Documents and installed your version.
The same issue remains and my overlay looks roughly like this:
![3capframex](https://user-images.githubusercontent.com/70185861/91504732-3c40ad00-e8ce-11ea-92be-2b7c7467d839.JPG)

If I reset on the overlay tab I still get all those duplicate entries, with many of them not even working.

Here is the log:
[CapFrameX.log](https://github.com/CXWorld/CapFrameX/files/5139169/CapFrameX.log)

The program works great but the overlay is just messed up every time, I can only fix them by using a older overlay json backup that I have. It has worked great prior to 1.5.3.

**Comment by DevTechProfile** [comment]
What do the following apps show?

* Taskmanager
* CPU-Z
* MSI Afterburner

**Comment by Taxxor90** [comment]
Seeing that you only got two core clock values in your screenshot, what is the openhardwaremonitor software stating for you? It doesn't show threads but it should give you loads and clocks for 16 cores.

**Comment by Kyouki-DotExe** [comment]
Task manager:
![taskmanager](https://user-images.githubusercontent.com/70185861/91581817-4060df00-e94f-11ea-895a-9902326d4b22.JPG)

CPU-Z:
![CPU-Z](https://user-images.githubusercontent.com/70185861/91581825-448cfc80-e94f-11ea-9b47-df0c075f35e6.png)

MSI Afterburner:
![MSI Afterburner v4 6 2 hardware monitor](https://user-images.githubusercontent.com/70185861/91581838-4951b080-e94f-11ea-9d31-f225b479d756.png)

Open hardware monitor:
![Open Hardware Monitor](https://user-images.githubusercontent.com/70185861/91581848-4eaefb00-e94f-11ea-8bfb-cade569460ad.png)

As requested all seem to work fine.

**Comment by DevTechProfile** [comment]
This version contains more logging but also a bugfix. Please try this. https://nexus.cluster.the.mind-blowing.dev/service/rest/repository/browse/CapFrameX/release__1.5.4/28.08.2020/

Just like before delete the old log files and than send me the new one.

**Comment by Kyouki-DotExe** [comment]
Log: [CapFrameX.log](https://github.com/CXWorld/CapFrameX/files/5144717/CapFrameX.log)

This is how it looks like now:
![overlay](https://user-images.githubusercontent.com/70185861/91627172-d3346480-e9b5-11ea-9ac4-3b5fa73366fe.JPG)

This looks on a per ccx now?

**Comment by DevTechProfile** [comment]
I've reworked the CPU sensor detection. A bugfix will follow soon.

**Comment by DevTechProfile** [comment]
Here's a new beta with a potenial bugfix. Please try this. You only need to share the log file if there're any problems. 

https://nexus.cluster.the.mind-blowing.dev/service/rest/repository/browse/CapFrameX/release__1.5.4/31.08.2020/ 
(Mon Aug 31 21:13:55 UTC 2020 )

**Comment by Kyouki-DotExe** [comment]
Seems to work splendid! Thank you very much. Hopefully this is the last time we see the bug.
