### ISSUE TITLE
No Tab except for Capture and Overlay is working.

### ISSUE THREAD

**Issue by EstoyMejor** [CXWorld/CapFrameX#134]
So, i dont really know what to report here, its not like i have a crash or something. 
When i Open the tool, get to the Capture Tab, everything works, i make a capture and it saves it succesfully. (Link to file below)
But when i try to open any tab except the Capture and Overlay tab, it just doenst open. Nothing changes. It just stays as the tab i last open (so either capture or Overlay). 

Link to the files (uploaded to my own Nextcloud): https://estoymejor.de/nextcloud/index.php/s/c4FgNJcXo5nxEYk

**Comment by DevTechProfile** [comment]
Can you please attach the log files under MyDocuments\CapFrameX\Logs?

**Comment by EstoyMejor** [comment]
Sorry for the accidental close. 

So, the 2nd Reeinstall fixed it now. So it does work now! Still added the Log to the files.
