### ISSUE TITLE
Zero Rpm - Gpu Fan (%) Issue

### ISSUE THREAD

**Issue by Eracore** [CXWorld/CapFrameX#139]
While in "Zero Rpm Mode"  "Gpu Fan (%)" shows wrong number in overlay screen.
Fans are not spinning but "Gpu Fan (%)" showing 41%.
Both must be "0" and should show % after fans start spinning.

Here is the screenshot.
[https://hizliresim.com/Aky3pa](url)

**CapframeX 1.5.5 Beta**
Ryzen 3700x -B450m Mortar - Vega 56 Pulse
Adrenaline 20.8.3 -Win 10 2004

**Comment by DevTechProfile** [comment]
Can you please compare the fan speed to HWiNFO please. Does HWiNFO show the correct numbers?

**Comment by Eracore** [comment]
CapframeX values are same with HWiNFO.. But HWiNFO is also wrong.
How can a fan has 39% rpm while its fan is not spinning ?
Here is the screenshot

[https://hizliresim.com/uxCUoY](url)

**Comment by DevTechProfile** [comment]
If CapFrameX and HWiNFO are both wrong it's most likely a driver issue. If the driver outputs a wrong value, there is nothing we can do. The only thing I can do is to check against the RPM.

Here's a beta: https://nexus.cluster.the.mind-blowing.dev/service/rest/repository/browse/CapFrameX/release__1.5.5/15.09.2020/

Tue Sep 15 12:35:42 UTC 2020 | 68016601

**Comment by Taxxor90** [comment]
> How can a fan has 39% rpm while its fan is not spinning ?

Does that value change while the fan is off?
If not, I'd assume the driver ist just reporting the last value it had before the fan went to 0.

**Comment by Eracore** [comment]
With latest beta Tue Sep 15 13:11:00 UTC 2020 | 82112775 |
I tried with heavy gaming and some emulation.
Problem fixed. Thanks guys.

Zero Rpm = %0
When fans spin % values are correct.
![Clipboard01+](https://user-images.githubusercontent.com/71212086/93308255-b3e96400-f80a-11ea-8cee-daabc51e7161.png)
![Clipboard02](https://user-images.githubusercontent.com/71212086/93308269-b946ae80-f80a-11ea-97d8-2a2e4fec799e.png)
