### ISSUE TITLE
A chocolatey package would be pretty useful

### ISSUE THREAD

**Issue by brian6932** [CXWorld/CapFrameX#142]
It would make for easier installs and easier updating

**Comment by awinnen** [comment]
Hi, we have received your request. We have discussed it and have come to the following conclusion:

We are sorry to say that we do not have the resources to provide a Chocolatey build at the moment.
However, we plan to integrate an updater into CX in one of the future versions, which will make updating easier.

**Comment by DevTechProfile** [comment]
Too much effort.
