### ISSUE TITLE
CX fails to create log file when capturing Timespy 

### ISSUE THREAD

**Issue by DevTechProfile** [CXWorld/CapFrameX#145]
Question: Is the process detected correctly?

**Comment by Marctraider** [comment]
Yes.

**Comment by DevTechProfile** [comment]
> Yes.

Please attach latest log file unter MyDocuments\CapFrameX\Logs

**Comment by Taxxor90** [comment]
preferably right after you tried to capture timespy^^

**Comment by DevTechProfile** [comment]
The only way to reproduce the "error" is to let CX run across all test sequences of Time Spy benchmark. This causes a process detection/hook loss.
