### ISSUE TITLE
CapFramex not saving captures.

### ISSUE THREAD

**Issue by x1lly** [CXWorld/CapFrameX#147]
So I usually don't test things because capframex I always knew wasn't going to work, but recently I found a fix that let me test only once. After that one time all my tests that I do, don't show up in captures and don't save. Yes, the overlay shows and the process is there in capframex. I've tried changing the capture bind, the time for capturing and the directory for saving. This could be because I'm on Windows 10 version 1709, but I know people who have the same version and have no issues what so ever. I've switched versions from the 1.5.5 to the new beta version 1.5.6. I didn't bother with the older versions since it seemed like there is something wrong with my installation.

**Comment by DevTechProfile** [comment]
Maybe you have activated the run history on the overlay page. So you need at least 3 runs to create one file.

**Comment by x1lly** [comment]
Ok, I'll try it and see how it goes

**Comment by Taxxor90** [comment]
A Screenshot of the expanded infobox on the capture page  after you finished a benchmark and the latest log file in your Documents folder would be helpful

**Comment by x1lly** [comment]
> 
> 
> Maybe you have activated the run history on the overlay page. So you need at least 3 runs to create one file.

Nope, its off

**Comment by x1lly** [comment]
[CapFrameX_001.log](https://github.com/CXWorld/CapFrameX/files/5322385/CapFrameX_001.log)

**Comment by DevTechProfile** [comment]
Please expand "Infobox" on the capture page and do at least one capture session. Send us the screenshot just like below.

![grafik](https://user-images.githubusercontent.com/30285858/95011133-d82ca980-062e-11eb-94b2-25bb23659bab.png)

**Comment by awinnen** [comment]
Can you please verify that the file CapFrameX.RTSSInterface exists in your CapFrameX installation Directory (C:\Program Files (x86)\CapFrameX)?

If not, does it exist after reinstalling CapframeX?

Do you have any aggressive antivirus installed?

**Comment by x1lly** [comment]
> 
> 
> Can you please verify that the file **CapFrameX.RTSSInterface.dll** exists in your CapFrameX installation Directory (C:\Program Files (x86)\CapFrameX)?
> 
> If not, does it exist after reinstalling CapframeX?
> 
> Do you have any aggressive antivirus installed?

No antivirus, I tried both portable and setup, neither work, and yes it exists after reinstalling or installing.

**Comment by x1lly** [comment]
> 
> 
> Please expand "Infobox" on the capture page and do at least one capture session. Send us the screenshot just like below.
> 
> ![grafik](https://user-images.githubusercontent.com/30285858/95011133-d82ca980-062e-11eb-94b2-25bb23659bab.png)

![image](https://user-images.githubusercontent.com/70561072/95093125-0cb36a80-06ee-11eb-9442-570ad804acf0.png)

**Comment by DevTechProfile** [comment]
Can you share the latest log file please?

**Comment by x1lly** [comment]
[CapFrameX_001.log](https://github.com/CXWorld/CapFrameX/files/5328046/CapFrameX_001.log)
Sure

**Comment by Taxxor90** [comment]
The error occurs when there is no capture data to process, so PresentMon didn't send any data for thet benchmark run.
I'd try a newer Windows 10 version because evne if there are people that don't have problems with it, depending on the system and the processes you want to capture, PresentMon can have trouble with this version.

**Comment by x1lly** [comment]
I mean, I want to be able to test different versions and how they impact frametimes, fps or whatever, surely there's a way to fix this

**Comment by Taxxor90** [comment]
Not from our side, if PresentMon doesnt deliver any data, there is nothing we can do about it.

**Comment by x1lly** [comment]
Pain, alright thanks for your time
