### ISSUE TITLE
Feature request: make it possible to select a custom interval in a graph

### ISSUE THREAD

**Issue by resadent** [CXWorld/CapFrameX#148]
Today I was trying to get 20 seconds out of a record I took in a game and found out I couldn't. Using the mouse scroll bar for zooming in and out is really not precise. It would be nice to have a matlab-like feature so you could select the x and y axis intervals. Like for example: x axis 20-40s, y axis 10-20ms.

I don't know if I'm explaning myself clearly enough, I think I do. Please point to me otherwise.

**Comment by Taxxor90** [comment]
You ca nset the Y axis on the analysis page, although it's limited to selected ranges (0-10, 0-20, 0-40, 0-60, 0-80, 0-100)

And the X axis range can be freely set via the range slider, this works for analysis aswell as comparison page

-

**Comment by resadent** [comment]
Alright I just saw the help part of CapframeX and with that I can do what I want. Also saw those Y ranges. It would be nice to have a custom range selector, where you can precisely specify the ranges you want. If anyone has the time and will to do that in the future 👍 .
