### ISSUE TITLE
Baldur's Gate 3 Dx11/Vulkan Frame Rate Report Issue

### ISSUE THREAD

**Issue by Eracore** [CXWorld/CapFrameX#149]
Baldur's Gate 3 Early access demo frame rate shows wrong.
I did check both with DX11 and Vulkan APIs.
Game normally runs 60fps+ but overlay shows very low fps.

R7 3700x + MSI B450m Mortar + DDR4 3600 32gb + Vega 64
CapframeX 1.5.6.3 Latest Beta + Adrenaline 20.9.2

Here is short snipped.
https://www98.zippyshare.com/v/eWLlwilq/file.html

**Comment by DevTechProfile** [comment]
Does Afterburner + RTSS show the correct FPS?

**Comment by Eracore** [comment]
Yes Afterburner + RTSS are showing correct FPS

https://hizliresim.com/cQ1gGk

**Comment by DevTechProfile** [comment]
Select the process in the process list on the Overlay page. Does this help? Which version do you use?

**Comment by Eracore** [comment]
Game wasn't in the process list. I had to close CapframeX and RTSS and restart all while game is running in background. 
Now it's fixed 👍👍

**Comment by DevTechProfile** [comment]
If the game is not in the process list you can just click the reset button above. This triggers a process redetection.

**Comment by Taxxor90** [comment]
Just FYI, the FPS you see in our overlay are not always the FPS of the game you're looking at, these are the fps of the process recongized by CX.
So you probably had some other process in there, that was not the game(maybe a launcher?) so you see the FPS for that one. And if you have multiple processes at the same time, your FPS will show 0.

**Comment by Eracore** [comment]
Thanks for the info Taxxor90... Baldur's Gate 3 runs from its own launcher. I guess thats why fps was wrong . After game started when I Alt+Tabbed to CapframeX I saw game wasn't in the process list. Neither launcher was in list. When I restarted CX game added to process and showed correct FPS.
