### ISSUE TITLE
[FR] Add an option to display filename (without ext) instead of executable name from table

### ISSUE THREAD

**Issue by Kein** [CXWorld/CapFrameX#150]
As title states. I'm comparing between different presentation modes, isolated to single executable, and I name my table files accordingly, but the tool always grabs executable name so it is ogre. I understand since you can capture multiple application via PM it kinds makes sense but different mode where I can set "Display filename for tables with single-exe capture" would be nice. This way it all should be inter-compatible.

**Comment by Taxxor90** [comment]
I don't know if I understand this correctly, but couldn't you just write the presentation mode and all other info in the "Comment" line `that is also present in the table?

**Comment by Kein** [comment]
Does not let me add comment for some reason

**Comment by Taxxor90** [comment]
Maybe dumb question but where are you trying to type the comment?^^ 
The right spot would be at the bottom left where the individual game name and HW configurations are displayed, comment being the bottom line.

**Comment by Kein** [comment]
Yeah, sure, the issue is that I need to know which is which and when I have 7 entries eahc for GameX I cant tell which is which because there are no identification besides framedata so I need to open each and try to calculate some data to see what matches what. It is pitful.

**Comment by Taxxor90** [comment]
Well but you also would need to know this when you are renaming your files, right? 
So just as you've probably renamed each file after you made a bench to state the presentation mode, you can add the comment for each record after you made it.

**Comment by Kein** [comment]
What.
I dont understand, you are going to great lengths to convince me, with some silly and tedious workarounds, that usability and QoL feature I request is not worth it.
Whatever

**Comment by DevTechProfile** [comment]
Please don't close the issue. It's just a discussion.
