### ISSUE TITLE
Missing auto-disable overlay option in 1.5.7 beta

### ISSUE THREAD

**Issue by siegmour** [CXWorld/CapFrameX#155]
I have a clean install of the 1.5.7 beta (Windows has been clean re-installed and I haven't copied any settings from a previous installation), but the auto-disable overlay feature is missing. Instead, only "overlay toggle" is displayed as in previous version. I am attaching a screenshot.

Thank you!

![image](https://user-images.githubusercontent.com/65442630/103441321-c1114e00-4c55-11eb-968e-102d3390f26e.png)

**Comment by Taxxor90** [comment]
Where did you download this version? 
All downloadable versions of 1.5.7 have this option since November 13th, so the current github version aswell as the one from our website

**Comment by DevTechProfile** [comment]
Just download the latest version: https://www.capframex.com/download

**Comment by siegmour** [comment]
Interesting, as suggested I re-downloaded 1.5.7 beta and confirm it's working now! Thank you for the help, closing the issue!
