### ISSUE TITLE
PresentMon now works under limited user, remove mandatory admin rights

### ISSUE THREAD

**Issue by Kein** [CXWorld/CapFrameX#156]
There is no reason to fail to start if no access elevation is available, PresentMon fixed the issue with capturing user processes: https://github.com/GameTechDev/PresentMon/issues/96

Since CapFrameX is already fetches list of available processes, whatever it sees running under user without elevation - the same will see PM. If user wants system process he will restart it as an admin.

**Comment by DevTechProfile** [comment]
Which start failure do you mean? PM is not the only reason for starting CX with admin rights. 

Do you mean the Verb start parameter?

`Process process = new Process
  {
      StartInfo = new ProcessStartInfo
      {
          FileName = startinfo.FileName,
          Arguments = startinfo.Arguments,
          UseShellExecute = startinfo.UseShellExecute,
          RedirectStandardOutput = true,
          RedirectStandardError = true,
          RedirectStandardInput = true, // is it a MUST??
          CreateNoWindow = startinfo.CreateNoWindow,
          Verb = "runas",
      }
  };`

"runas" does not seem to be necessary any longer.

**Comment by Kein** [comment]
Why would you unironically want a user-space software that collect stats about a videogame run as admin FORCED and DEFAULT?
What possible unavoidable need you have to outright not work without admin rights and potential security issue?

**Comment by DevTechProfile** [comment]
Because we need read access to C:\. Because OpenHardwareMonitor needs it like HWiNFO64, GPU-Z or Ryzen Master.

**Comment by Kein** [comment]
Why do you need write access to root of C:\? The rest can be made available only if users runs it as admin, that is widely accepted and pretty normal approach.

**Comment by DevTechProfile** [comment]
It's also pretty normal if the app is running without admin rights that dozens of users will come to use and ask why the sensor logging and overlay don't work any longer.

We have no Windows certificate btw. And I don't think we will get one for free.

**Comment by Kein** [comment]
Your lack of understanding basic security has nothing to do with certificates.

**Comment by awinnen** [comment]
> Your lack of understanding basic security has nothing to do with certificates.

If you know how to achieve to run CX without elevated permissions, feel free to develop it yourself and contribute your changes as pull request to our project.

Your contribution is highly appreciated.
