### ISSUE TITLE
Adding the 'Custom title' and 'Context' features on the Analysis page

### ISSUE THREAD

**Issue by RodroG-85** [CXWorld/CapFrameX#157]
Hello,

Basically, my suggestion would be to add both the _Custom title_ and _Context_ features on the Analysis page, just like on the Comparison page, or one of them.

**Comment by Taxxor90** [comment]
Everything that could be set as a context on the Comparison page is already included in the system info expander on the Analysis page so you already have all 5 available contexts visible at once.

As for the custom title, yes that can indeed be done and is easy to implement.

**Comment by Taxxor90** [comment]
![CX_2021-02-07_19-07-51_Star Wars Battlefront II_Ultra Preset DX11 (Frostbite 3 0) - Custom Scene  Pillio ](https://user-images.githubusercontent.com/45570250/107155280-e3466c00-6977-11eb-84eb-a0d92717efbe.png)

**Comment by RodroG-85** [comment]
> Everything that could be set as a context on the Comparison page is already included in the system info expander on the Analysis page so you already have all 5 available contexts (and more) visible at once.

You are right. I agree with you.

> As for the custom title, yes that can indeed be done and is easy to implement.

Perfect, thank you @Taxxor90 . I'm happy to hear that. The example looks good.

**Comment by Taxxor90** [comment]
If you need it for something right now, it's the latest build in our archive
https://archive.capframex.com/
