### ISSUE TITLE
CapFrameX 1.5.8 not automatically detecting games Feature request add game per exe

### ISSUE THREAD

**Issue by iNgeon** [CXWorld/CapFrameX#158]
CapFrameX 1.5.8 is not automatically detecting some games.
Feature request to manually add game per exe or folder it is installed.
Currently there is Running processes and Process ignore list and it is in neither.
It keeps showing scanning for process...

Games trying to monitor shows but does not process, still works in 1.5.7 but not in 1.5.8

![MWSnap 2021-02-10, 18_40_04](https://user-images.githubusercontent.com/3817692/107541116-762d1380-6bcf-11eb-81c1-465e895cff33.jpg)

**Comment by Taxxor90** [comment]
did you try the rescan button an it's still not showing up?

**Comment by DevTechProfile** [comment]
The most important question is, do you use the portable version? Better try the installer...

**Comment by iNgeon** [comment]
> The most important question is, do you use the portable version? Better try the installer...

Yes up till now always do. Prefer them

**Comment by DevTechProfile** [comment]
Does the detection now work with the installer version?

**Comment by Taxxor90** [comment]
> unless its just some pre-compiled list that ships by default

That's the case

**Comment by Zusier** [comment]
> 
> 
> Does the detection now work with the installer version?

Have the same issue, setup version worked.

**Comment by DevTechProfile** [comment]
> Have the same issue, setup version worked.

From which location/folder do you start the portable?

**Comment by Zusier** [comment]
F:\Bench\CapFrameX\CapFrameX.exe

**Comment by DevTechProfile** [comment]
I've just checked the portable. The problem is obvious. Important components are missing because there's a build definition bug. Fix will come soon!

**Comment by DevTechProfile** [comment]
Fixed portable: https://www.capframex.com/download
