### ISSUE TITLE
How to make graph smaller by horizontal?

### ISSUE THREAD

**Issue by audimatic** [CXWorld/CapFrameX#159]
Sorry, maybe im really stupid, but i cant find a option how to make graph smaller by horizontal, so here only 1 question how can i make a graph smaller and where are this "setting" is located? and im actually googled it, but i didnt find anything about this option

**Comment by Taxxor90** [comment]
The controls for the graphs are explained in the manual

https://github.com/CXWorld/CapFrameX#chart-control

**Comment by audimatic** [comment]
is it for overlay?

**Comment by DevTechProfile** [comment]
If you want adjust the size of the RTSS overlay graphs the only way to do this is to use "On Screen Display zoom" option from RTSS itself. We have currently no options for scaling graphes on the overlay.
