### ISSUE TITLE
autostart without uac dialog

### ISSUE THREAD

**Issue by JanHBade** [CXWorld/CapFrameX#160]
Hello,

great program!

The autostart option should implented as scheduled task, not as registry key.

Then the uac dialog is gone, look at HwInfo/MsiAfterburner that makes that similiar

<<DOcean from the PCGH Extreme forum

**Comment by Taxxor90** [comment]
Implemented in 1262c9bb8025b045c168cc545de4e8f9e75b2702 and scheduled for version 1.6.6
