### ISSUE TITLE
Ignore list issue

### ISSUE THREAD

**Issue by Marko647** [CXWorld/CapFrameX#163]
Even though I added iCue to ignore list, it still shows overlay on it.

**Comment by Taxxor90** [comment]
The Ignore list controls the apps that are recognized by the capture service and has nothing to do with the overlay.

If you want an app to not show the overlay on it, add a new profile for that app in RTSS and deactivate "On-Screen Display support" for that profile.

**Comment by Marko647** [comment]
Super cool, thanks !
