### ISSUE TITLE
add to Windows Package Manager repository

### ISSUE THREAD

**Issue by Kyouki-DotExe** [CXWorld/CapFrameX#171]
Issue: `winget search CapFrameX` does not give me any results :(

Would it be possible to add CapFrameX to the repository so I can grab updates from there? That would be awesome as it's a great tool I use daily on more and more machines.

Wasn't too sure how to "suggest" this properly but this could be added as enchantment. 

Thanks in advance! Love the tool so far.

**Comment by awinnen** [comment]
Hi

thanks for your request. Unfortunately we cannot add CapFrameX to the Windows Package Manager for at least 2 reasons:

1. Currently we don't sign the Application with a Code-Signing Certificate. Thats the reason why you might get a security warning before installing the Software. It won't be distributed without being signed.
2. CapframeX needs to run as Administrator. For distribution through Windows Package Manager, software must be able to run without Administrator privileges.
3. Submitting an update to Repositories is quite a lot of work. We don't really have the time to to bundle our application for various Package Managers and ensure they are updated regularly.

Therefore we cannot add it to the Windows Package Manager. Some of the Reasons listed above also apply to other package managers like chocolatey.
