### ISSUE TITLE
Query: Monitoring disk activity

### ISSUE THREAD

**Issue by iNgeon** [CXWorld/CapFrameX#173]
Any possibility to add monitoring of disk activity/usage.
Even if basically just to break down disk read\write or i\o usage down by the individual hard drives or say that specified drive and plot

**Comment by DevTechProfile** [comment]
What about using HWiNFO for this? You can just add the monitoring data to the RTSS overlay or do you want to log these data?

**Comment by DevTechProfile** [comment]
Closed because sensor types are currently limited to CPU, GPU and RAM.
