### ISSUE TITLE
Application Latency is not fully implemented

### ISSUE THREAD

**Issue by Naworm** [CXWorld/CapFrameX#176]
Application Latency is not fully implemented

- App Latency is not captured
- So we cannot make comparison with App Latency
- App Latency value is only integral, please allow `5.95ms` instead of `5ms`

**Comment by Taxxor90** [comment]
App latency isn't captured directly as standalone unit. It's a calculation based on multiple values.
You can check it in the sync tab(it's only integral on the overlay, though we could give it decimal values here in the next version).

**Comment by Naworm** [comment]
Oh thank you @Taxxor90 I've missed the sync tab.
Great !
But I saw that we cannot compare imput lag with multiples captures like comparison tab, do you plan to implement it too?

**Comment by Taxxor90** [comment]
The comparison tab is only for comparing FPS values to have all bars refer to the same value type.
What I could do is add the average input lag to the report page so you could compare it there.
