### ISSUE TITLE
Implement Render Latency

### ISSUE THREAD

**Issue by Naworm** [CXWorld/CapFrameX#177]
Please implement Render Latency, like NVIDIA FrameView SDK does.

![image](https://user-images.githubusercontent.com/48997616/128646174-94918050-0d03-4003-94db-11c0f3a3ae0c.png)

**Comment by DevTechProfile** [comment]
We have implemented an Application Latency. This corresponds to the "PC Latency" in graphic below. We think that this is a meaningful metric and therefore sufficient.
![grafik](https://user-images.githubusercontent.com/30285858/134722503-735f0a55-c961-4cfc-a88e-63c1e2322a75.png)
