### ISSUE TITLE
Capeframex v1.6.4 Graph no longer displays when enabled

### ISSUE THREAD

**Issue by iNgeon** [CXWorld/CapFrameX#178]
Enabling Framerate and or Frametime graph no longer displays the graph in game.
Is this a big or something i'm possibly doing wrong?
Running this with Guru3D RTSS Rivatuner Statistics Server Download 7.3.2 Beta 2
Think i found it, toggling OSD of brings up the graph, so its either a bug or OSD anf framerate needs to have an AND or OR tied to it. Seems it also not possible to enable both Framerate and Frametime graphs and OSD like we use to at the same time

**Comment by Taxxor90** [comment]
I have no problems displaying both grahps at the same time and toggling the OSD on and off.
Maybe your overlay has too many lines? There's a limitation how much can be displayed at once.

**Comment by DevTechProfile** [comment]
related to: https://github.com/CXWorld/CapFrameX/issues/181
