### ISSUE TITLE
Overlay items are cut off after a certain amount

### ISSUE THREAD

**Issue by DevTechProfile** [CXWorld/CapFrameX#181]
Measure: compress content/hypertext further

**Comment by DevTechProfile** [comment]
Download >=Build 17: https://archive.capframex.com/

**Comment by iNgeon** [comment]
Ah I have this same Question.
How can one see the maximum amount if items that can be displayed in overlay. I have a bunch of things ticked and usually it cuts off somewhere and usually the frame fps or frame time graph does not get displayed with alot of items ? (I usually only use the frame rate one) Have this on most builds example 1.7.4 and 1.7.5 Beta atm
