### ISSUE TITLE
CapframeX Doesn't autostart.

### ISSUE THREAD

**Issue by Gatki** [CXWorld/CapFrameX#185]
CapframeX Doesn't start with windows. I do not know why I check in program.

**Comment by DevTechProfile** [comment]
Thanks for reporting. Which CapFrameX version do you use, which Windows version? Does an entry exists in the Windows Task Scheduler?

**Comment by Gatki** [comment]
Cap 1.6.6, Windows 11, no entry.

**Comment by DevTechProfile** [comment]
Please upload the log files under MyDocuments\CapFrameX\Logs or send it as a Zip file to contact@capframex.com.

**Comment by Gatki** [comment]
I found this entry
`{"@t":"2021-12-08T16:04:06.3819232Z","@mt":"Unable to perform autostart task","@l":"Error","SourceContext":"CapFrameX.ViewModel.ColorbarViewModel"}`
but I also sent the log: D

**Comment by DevTechProfile** [comment]
You can try to create the entry manually. The reason for the error is not clear. It's maybe due to a virus scanner and/or detection programs.

**Comment by Gatki** [comment]
The only antivirus I have is Windows Defender.

**Comment by DevTechProfile** [comment]
Closed because not  reproducible issue.
