### ISSUE TITLE
Just stopped working for me

### ISSUE THREAD

**Issue by Muszek1996** [CXWorld/CapFrameX#187]
Hi, I was successfully using program until one pc restart, now it's not working, tried multiple versions portable and installer, when I turn it on nothing happens. Only error I got is error "Already an instance running", how to diagnose it? I can't find any log file. No capframe in tray, I can see only process in task manager with still 22 460K of memory taken depending on version.

I left it "running" overnight, 24 124K memory usage and any gui still not visible

**Comment by Muszek1996** [comment]
I just realised about capframe store files in documents, then I found logs file, and now I see that error is related due to corrupted file, I crashed when I was recording that's why it's corrupted. 
`{"@t":"2021-12-29T01:59:24.3966387Z","@mt":"Unable to load Configuration from path C:\\Users\\Muszek\\OneDrive\\Documents\\CapFrameX\\Configuration\\AppSettings.json","@l":"Error","@x":"System.Exception: Configurationfile C:\\Users\\Muszek\\OneDrive\\Documents\\CapFrameX\\Configuration\\AppSettings.json is corrupted\r\n   w CapFrameX.Configuration.JsonSettingsStorage.Load() w D:\\Jenkins\\workspace\\CX-App_master\\source\\CapFrameX.Configuration\\JsonSettingsStorage.cs:wiersz 95","SourceContext":"CapFrameX.Configuration.JsonSettingsStorage"}
{"@t":"2021-12-29T01:59:24.4236627Z","@mt":"Unhandled exception in CapFrameX v1.6.5.2","@l":"Fatal","@x":"System.Reflection.TargetInvocationException: Obiekt docelowy wywołania zgłosił wyjątek. ---> System.Exception: Configurationfile C:\\Users\\Muszek\\OneDrive\\Documents\\CapFrameX\\Configuration\\AppSettings.json is corrupted\r\n   w CapFrameX.Configuration.JsonSettingsStorage.Load() w D:\\Jenkins\\workspace\\CX-App_master\\source\\CapFrameX.Configuration\\JsonSettingsStorage.cs:wiersz 105\r\n   w CapFrameX.Configuration.CapFrameXConfiguration..ctor(ISettingsStorage settingsStorage) w D:\\Jenkins\\workspace\\CX-App_master\\source\\CapFrameX.Configuration\\CapFrameXConfiguration.cs:wiersz 638\r\n   --- Koniec śladu stosu wyjątków wewnętrznych ---\r\n   w System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)\r\n   w System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)\r\n   w System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark& stackMark)\r\n   w System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)\r\n   w System.Activator.CreateInstance(Type type, Object[] args)\r\n   w DryIoc.SingletonScope.GetOrAddItem(Object[] bucket, Int32 index, CreateScopedValue createValue)\r\n   w DryIoc.SingletonScope.GetOrAdd(Int32 id, CreateScopedValue createValue)\r\n   w DryIoc.ReflectionFactory.CreateServiceExpression(MemberInfo ctorOrMember, Expression factoryExpr, Expression[] paramExprs, Request request)\r\n   w DryIoc.ReflectionFactory.CreateExpressionOrDefault(Request request)\r\n   w DryIoc.Factory.GetExpressionOrDefault(Request request)\r\n   w DryIoc.Factory.GetDelegateOrDefault(Request request)\r\n   w DryIoc.Container.ResolveAndCacheDefaultDelegate(Type serviceType, Boolean ifUnresolvedReturnDefault)\r\n   w CapFrameX.Bootstrapper.ConfigureContainer() w D:\\Jenkins\\workspace\\CX-App_master\\source\\CapFrameX\\Bootstrapper.cs:wiersz 80\r\n   w Prism.DryIoc.DryIocBootstrapper.Run(Boolean runWithDefaultConfiguration)\r\n   w CapFrameX.App.OnStartup(StartupEventArgs e) w D:\\Jenkins\\workspace\\CX-App_master\\source\\CapFrameX\\App.xaml.cs:wiersz 49\r\n   w System.Windows.Application.<.ctor>b__1_0(Object unused)\r\n   w System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)\r\n   w System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)"}
`
contents of AppSettings.json :

`0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000
0000 0000 0000 0000 0000 0000 0000 0000`

I think It is good idea to handle this kind of error in future releases. Deleted file and my problem is solved now.

**Comment by awinnen** [comment]
thanks for your report. We will show a alert in future releases if this problem occurs. So the User can delete the config file without having to look in the Logfile.
