### ISSUE TITLE
0x80070666 when installing vc_redist.x64.exe

### ISSUE THREAD

**Issue by he3als** [CXWorld/CapFrameX#189]
## Explanation
CapFrameX was not working due to an unknown reason (possibly corruption) so I decided to reinstall it. However (after uninstalling), I get this error message in CapFrameX and it seems like the installer is failing due to `vc_redist.x64.exe` not installing due to it already being installed (I presume from the previous installation).

## Diagnostic Info
Log: [CapFrameX_Capture_and_Analysis_Tool_20211229200636.log](https://github.com/CXWorld/CapFrameX/files/7790471/CapFrameX_Capture_and_Analysis_Tool_20211229200636.log)

![image](https://user-images.githubusercontent.com/65787561/147700036-7b761560-3c01-4d70-b771-a58b919a6dbe.png)

**Comment by DevTechProfile** [comment]
Have you uninstalled the other Visual C++ Redistributable Package version? Not sure how we can solve this problem from our side.

**Comment by he3als** [comment]
> Have you uninstalled the other Visual C++ Redistributable Package version? Not sure how we can solve this problem from our side. 

What is it called?

**Comment by DevTechProfile** [comment]
MS Visual C++ 2015-2019 Redistributable 

![grafik](https://user-images.githubusercontent.com/30285858/147826303-51bc2685-fcc1-41f3-9851-c4db82df6a0d.png)

**Comment by he3als** [comment]
Thank you, maybe there could be detection in the future to automatically check if these redistributables are installed?

**Comment by DevTechProfile** [comment]
There is actually such detection in the installer. But something strange went wrong on your sys.
