### ISSUE TITLE
Expose the SensorSnapshotStream through the web API

### ISSUE THREAD

**Issue by farnoy** [CXWorld/CapFrameX#193]
It would be cool to have access to the same sensor data that I've enabled for logging, but over the web API. It could be a websocket interface or an HTTP endpoint.

I'd like to log this data myself, even when I'm not actively making captures through CapFrameX.

**Comment by awinnen** [comment]
Hi,

adding this feature would be possible.
Can you quickly describe your exact usecase?
Why would you want to log the sensordata all the time?

**Comment by farnoy** [comment]
I want to ingest it into Prometheus and keep track of my gaming sessions long-term. I'll probably only activate it when there's a process that CapFrameX is monitoring - the API for this is already available.

**Comment by awinnen** [comment]
Feature has been implemented. Its available in our current testing-build which is available in our archive. https://archive.capframex.com/

Websocket Url: ws://localhost:1337/ws/sensors

**Comment by farnoy** [comment]
That was quick! Thanks a lot. It's working great, but it's only sending data when the overlay is toggled on. Is that deeply ingrained into CapFrameX? Does it not check on sensors itself unless a capture is in progress or the overlay is enabled?

**Comment by farnoy** [comment]
I guess this is it?

https://github.com/CXWorld/CapFrameX/blob/c628b10c8d7647c9f6a310484d76e5e10eb59823/source/CapFrameX.Sensor/SensorService.cs#L89

Can `ActiveContexts` from the websocket modules be integrated into this conditional? So as long as someone's listening, it would fetch fresh sensor data and stream it.

On my end, I definitely won't keep it open 24/7, I'm thinking a check to `/processes` on an interval to see if a game is running and only opening up the ws stream then.

**Comment by awinnen** [comment]
sure. check out the latest build.

**Comment by Taxxor90** [comment]
> On my end, I definitely won't keep it open 24/7, I'm thinking a check to `/processes` on an interval to see if a game is running and only opening up the ws stream then.

I think, the way it's currently built in is fine. As long as you're not conneted to the WS, the stream is inactive. I can also think of situations where you might just want to track for example your CPU power without being in a game. Then you can also just connect to the WS.

**Comment by Taxxor90** [comment]
> It's working great, but it's only sending data when the overlay is toggled on.

Don't know if you noticed it, but the values it was sending, also with the latest version, should always be the same and some sensors should even be missing entirely. This was because while we send the sensor stream when the WS is connected, the sensors weren't actually updated unless they were selected in the "overlay items" list or in the "sensor" list while an active capture was running. So for any sensor not selected in the overlay items list, you'd always get the same value over and over again that was updated once at the start of CapFrameX, with some values also being null and thus not present in the WS output.

That's fixed with the latest build in the archive. Now, when connected to "ws/sensors" all sensors get updated and when connected to "ws/activesensors" all sensors selected on the "sensor" page get updated.


So with everything implemented and working as expected, I'm closing the issue.

**Comment by farnoy** [comment]
Strange, my email reply did not show up here as a comment, repasting:

I've tested it and so far it works perfectly. Thanks again for the quick turnaround.

Could you also make the OSD WebSocket stream data when there are active listeners? As of the latest build, it only seems to stream when the overlay is enabled by the user.

The use case is similar, since CapFrameX already calculates percentile frametimes, I'd log them along with sensor data.

**Comment by Taxxor90** [comment]
> Could you also make the OSD WebSocket stream data when there are active listeners? As of the latest build, it only seems to stream when the overlay is enabled by the user.

From a logical standpoint it makes sense that the overlay has to be enabled to stream the overlay.

You can hide the RTSS output via the checkbox in the remote options if you don't want to see it infame

**Comment by farnoy** [comment]
I see what you mean, that wouldn't make much sense.

From a remote client's perspective, having access to the online metrics that CX produces would be amazing. Perhaps a better idea would be to create an HTTP endpoint to expose `GetOnlineFpsMetricValue` through HTTP?

https://github.com/CXWorld/CapFrameX/blob/d588c743ba12b366ba35e49eb4aacbc8a62e0d4b/source/CapFrameX.PresentMonInterface/OnlineMetricService.cs#L301-L308

An endpoint like `GET /api/online-metrics?name=Average,P1`, where the `name` parameter is a comma separated list of metrics from

https://github.com/CXWorld/CapFrameX/blob/d45a6f61c2cff56d4dfe21b453decbc3e555d0dd/source/CapFrameX.Statistics.NetStandard/Contracts/EMetric.cs#L11-L19

Does this sound like a better idea? I'm sorry about bothering you so much, maybe you'd prefer if I created another GH issue?

**Comment by farnoy** [comment]
The reason I was suggesting these solutions is that I'd like to retain the ability to press Alt+O in any game and immediately have live performance data visible. If I check the "Hide OSD in RTSS" option to keep the stream for my exporter, I'd have to alt-tab and uncheck it during my gaming sessions.

> Also, the online metrics are called online metrics for a reason, they aren't supposed to be logged and averaged, for this you can do a proper capture

I agree completely, I wouldn't use this for actual performance comparisons, just a cursory look in the archives to visualize what process was running, what the performance was at a coarse level and how the hardware was used. I'd still use captures and comparisons within CX to get a detailed view.

The HTTP endpoint I suggested would also be superior to the current OSD stream, because it's structured data that's also independent of the user's configuration for the overlay. I understand if you don't want to spend time on this, but would you accept a contribution from me if implemented said endpoint?

I believe the Online metrics are being calculated even if the overlay is disabled, so to me this looks like a matter of exposing said metrics. It wouldn't have to change anything at the core of CX about how or when to calculate these.

**Comment by farnoy** [comment]
It took me a long time but I finally got around to it - https://github.com/farnoy/capframex-exporter

Maybe someone else will find it useful.

**Comment by farnoy** [comment]
I've tested it and so far it works perfectly. Thanks again for the quick
turnaround.

Could you also make the OSD WebSocket stream data when there are active
listeners? As of the latest build, it only seems to stream when the overlay
is enabled by the user.

The use case is similar, since CapFrameX already calculates percentile
frametimes, I'd log them along with sensor data.
