### ISSUE TITLE
CapFrameX causes Rainbow Six: Rogue Spear to crash

### ISSUE THREAD

**Issue by Ulver84** [CXWorld/CapFrameX#194]
Hi. 

- With CapFrameX running in the background I get an immediate crash when trying to start a mission. The game doesn't crash in the menus. 
- Closing CapFrameX and the game doesn't crash.
- I am presented with the following crash message (don't know if it matters): 

> OS: Windows NT 6.2 (Build: 9200)
> CPU: AuthenticAMD Unknown processor @ 3803 MHz with 2047MB RAM
> Video: AMD Radeon RX 6800 (2)
> 
> General protection fault!
> 
> History: UD3DRenderDevice::SetRes <- UGameEngine::Draw <- UWindowsViewport::Repaint <- UWindowsClient::Tick <- ClientTick <- UGameEngine::Tick <- UpdateWorld <- MainLoop
> 

Windows 10 Home
Version	21H2
build	19044.1620
Windows Feature Experience Pack 120.2212.4170.0

Ryzen 5800X (latest chipset driver)
RX 6800 (latest driver)
CapFrameX version 1.6.7 and 1.6.8.

**Comment by Taxxor90** [comment]
Sounds like it could be a PresentMon issue. Does it also happen when OCAT is open?

**Comment by Ulver84** [comment]
Hi Taxxor90. Sorry for the late reply. I couldn't get OCAT to work at all with any games that I tried.

**Comment by DevTechProfile** [comment]
Since PresentMon is based on ETW it shouldn't have any direct impacts on the game. Can you please try CapFrameX without RTSS running in the background.
