### ISSUE TITLE
Dungeon Keeper 2 isn't registered by CapFrameX

### ISSUE THREAD

**Issue by Ulver84** [CXWorld/CapFrameX#195]
Hi

I've tried to capture some stats from Dungeon Keeper 2 and get the overlay working (GOG release), but I can't get CapFrameX to hook the process. 

I've tried low, medium and high detection level, vector 3d and raster 3d, but I can't get the overlay working.

**System info**
Windows 10 Home
Version 21H2
build 19044.1620
Windows Feature Experience Pack 120.2212.4170.0

Ryzen 5800X (latest chipset driver)
RX 6800 (latest driver)
CapFrameX version 1.6.7 and 1.6.8.

**Comment by Taxxor90** [comment]
Does it work with other tools that are using PresentMon? Like Frameview or OCAT?
PresentMon works with DirectX 9-12, Vulkan and OpenGL, I'm pretty sure Dungeon Keeper 2 uses DirectX 7.

**Comment by Taxxor90** [comment]
I just installed the GOG version myself and it hook up fine for me. Didn't even need to rescan
![Screenshot 2022-03-28 194635](https://user-images.githubusercontent.com/45570250/160456815-1630e673-8616-4ac4-87ab-b3380a56810f.png)

Windows 11 21H2
Build 22000.588

Ryzen 5800X (latest chipset driver)
RX 6800 (latest driver)
CapFrameX version 1.6.8

**Comment by Ulver84** [comment]
Hi

> I just installed the GOG version myself and it hooked up fine for me. Didn't even need to rescan ![Screenshot 2022-03-28 194635](https://user-images.githubusercontent.com/45570250/160456815-1630e673-8616-4ac4-87ab-b3380a56810f.png)
> 
> Windows 11 21H2 Build 22000.588
> 
> Ryzen 5800X (latest chipset driver) RX 6800XT (latest driver) CapFrameX version 1.6.8

Hi Taxxor90

Perhaps I should have been more clear. It's the overlay that I'm trying to get working. Does it work for you? I haven't tested whether CapFrameX will capture data, but I will give it a go when I get home.

**Comment by Taxxor90** [comment]
Aaah, well yeah the overlay is not working for me but that has nothing to do with CapFrameX not detecting the game. The RTSS overlay is independent from our software, we only send data to it but have no control over on which games it actually shows up.

**Comment by Ulver84** [comment]
Noted. Thank you very much for the quick feedback, I guess you can just close this ticket then 🙂
