### ISSUE TITLE
Project TaigaCat Plugin Support for CFX

### ISSUE THREAD

**Issue by Kirby0Louise** [CXWorld/CapFrameX#197]
Hi, thought I'd create this thread to discuss how I should go about implementing Project TaigaCat's real time capture card analysis features into CapFrameX.  This is mostly useful for game console benchmarking (ala Digital Foundry).

I guess I'll start with my proposal on how it'll be implemented, please let me know any suggestions/tweaks you'd like to see and I'd be happy to investigate supporting/changing them

- Project TaigaCat for CapFrameX will be implemented as a separate plugin .dll
  - This .dll will of course be written in C#, open source under the MIT License in line with the rest of the program
  - I feel that keeping this functionality separate would be a better idea than natively adding it to the main application as the process for capture card based benchmarking differs from typical "native" PC benchmarking
  - This also allows the two to be worked on and updated (mostly) independently of each other
- CFX will call the plugin's init method, and the plugin will start-up and report back a list of all webcams connected to the PC (capture cards present themselves as virtual webcams)
- The user can select the appropriate capture device from CFX, which then will let the plugin know which device the user has selected
- The plugin then tells CFX how the capture card is configured (resolution, refresh rate, bit depth) so CFX has the info it needs to setup any recordings/graphs/whatever on the application side
  - If CFX needs any additional info than this just let me know
- CFX can request several things from the plugin
  - The current frame from the capture card
  - The current configuration of the plugin (capture card name, resolution, refresh rate, bit depth, and frame comparison confidence level)
  - Ask the plugin if a new frame has been rendered (aka attempt to determine if the source is dropping frames)
  - Ask the plugin what the current frametime/framerate is based on capture card analysis
  - Ask the plugin for the average, standard deviation and coefficient of variation for pixel differences of the last analysis
  - Change the target capture device and analysis confidence level
- Frame analysis currently is done by calculating a confidence level that two frames are the same
  - First the current/previous frames are converted to a 3D matrix with each table entry holding the RGB color channels of the appropriate pixel
  - The matrices are subtracted, and then we determine the distance in the RGB color space of each pixel from the previous frame's pixel
  - The average, standard deviation and coefficient of variation are determined
  - The frame's confidence level is simply 1.0 - the coefficient of variation
  - If the frame's confidence level exceeds the confidence level set by the user (in other words, we believe the frames are similar enough), then it's marked as a dropped frame

Apologies in advance for the wall of text (writing isn't my strong suit), and please let me know what suggestions/tweaks you'd like to see.  I'll try to have an alpha ASAP (though bear with me as I have a somewhat busy schedule and it's been a LONG time since I dealt with webcam access in .NET)

Cheers!

**Comment by DevTechProfile** [comment]
Thanks for kicking off the integration of TaigaCat @Kirby0Louise. Before were are diving into the details I would like to sketch the basic approach I am having in mind for external performance data. Actually PresentMon is an external source for use. We are connecting to the output stream of PresentMon. As an abstraction of an external source with a performance data stream we implement the following interface. 

```C#
public interface ICaptureService
{
	IObservable<string[]> RedirectedOutputDataStream { get; }

	Subject<bool> IsCaptureModeActiveStream { get; }

	Subject<bool> IsLoggingActiveStream { get; }

	bool StartCaptureService(IServiceStartInfo startinfo);

	bool StopCaptureService();

	IEnumerable<(string, int)> GetAllFilteredProcesses(HashSet<string> filter);
}
```

Btw, we can change this if required (naming and even functions or properties). The main part is the obserable stream "RedirectedOutputDataStream" (naming wouldn't fit to the TaigaCat integration I think).  It's a stream of arrarys of strings whereas each position is well defined. Each element of the stream represents a frame with present data like MsBetweenPresents or MsInPresentAPI and so on. The concept is different from your proposal "CX can request the current frame from the capture card" as we would like to connect to hot (RX term) data stream. Do you think it's possible? We can discuss the details like time stamping later.

Thanks for doing this. Looking foward to create a very cool feature for the community. 

Greets, Mark

**Comment by Kirby0Louise** [comment]
Thanks for the quick reply.

If you've already got an established interface for how performance data is supposed to be communicated to the application then I'm more than willing to use that.  I'll start working on setting up the interface into the plugin, I just need to know exactly what the expected format of each RedirectedOutputDataStream string array is, the rest seems fairly straight forward

**Comment by DevTechProfile** [comment]
Fyi, I am currently working on decoupling the abstraction/interface for external usage. 

>  I just need to know exactly what the expected format of each RedirectedOutputDataStream string array is, the rest seems fairly straight forward

You can just implement a Dictionary (Index, ParameterName). Gonna put in the interface.

**Comment by DevTechProfile** [comment]
Update: You can check out branch release/1.6.9. You will find the reworked interface "ICaptureService" in the project "CapFrameX.Capture.Contracts" which can now be implemented in your plugin. 

The interface contains info about the present data/parameter naming for the frame data stream. Just implement the Dictionary "ParameterNameIndexMapping". 

We get QPCTime by calling

C#´´´
[DllImport("Kernel32.dll")]
private static extern bool QueryPerformanceCounter(out long lpPerformanceCount);
´´´

**Comment by DevTechProfile** [comment]
Hey @Kirby0Louise, any updates on the TaigaCat plugin implementation?

**Comment by DevTechProfile** [comment]
No support from the TaigaCat dev so the issue can be closed.
