### ISSUE TITLE
How to enable / disable this options?

### ISSUE THREAD

**Issue by Rrhyast** [CXWorld/CapFrameX#199]
![CapFrameX_TSJNoALmFJ](https://user-images.githubusercontent.com/62977195/170372200-612c4e51-db9c-4e74-a527-a7e8f6aea545.png)

**Comment by DevTechProfile** [comment]
Give us more info about your sys please.

**Comment by Taxxor90** [comment]
These are not options you can set in CapFrameX, they just inform you about the status of these two features. 
Windows Game mode is activated through windows obviously.
And Resizable Bar is activated in the BIOS if your GPU supports it.

**Comment by DevTechProfile** [comment]
> Intel Core I7 6700HQ
> 
> NVIDIA GTX 1070 Mobile

Pascal does not support ResBar. Therefore, you will find no option to enable it.
