### ISSUE TITLE
Show frametimes for CPU/GPU separately.

### ISSUE THREAD

**Issue by GT500org** [CXWorld/CapFrameX#211]
fpsVR has a very handy feature where it displays frametimes separately for the CPU and GPU rather than showing the overall frametime. I find this information useful for better determining what is causing FPS issues, because at the very least I know what hardware the lengthy processing time or spikes in processing time are happening on even though I may not know the actual cause, which gives me a better idea of how to debug things when I run into issues.

Right now the only tool I know that allows you to look at latencies in flatscreen games that are broken down into more than just an overall frametime is SpecialK (see third screenshot), however it isn't exactly safe to use in multiplayer games (some people have reported getting banned from games when using it).

It would be awesome if CapFrameX could show frametimes for CPU and GPU separately like fpsVR does. SpecialK's output is nice for advanced analysis, but I don't know if most people would need that much data, unless of course they're doing latency analysis in reviews like Gamers Nexus does.

![vivaldi_TyCPuTqOS6](https://user-images.githubusercontent.com/18017139/181168714-c7dcae5d-5852-4b7d-9a1e-b64578abccbc.png)

![vivaldi_phgWslTZ2b](https://user-images.githubusercontent.com/18017139/181168740-b4ef535e-ff20-4842-a139-ddc276211a79.png)

![Indiana-Win64-Shipping_cNAq6pYwQx](https://user-images.githubusercontent.com/18017139/181169468-e42f4be4-8e7f-442b-b0b6-685b731d7761.png)

**Comment by Taxxor90** [comment]
Using PresentMon as our data source, we have no access to separate CPU and GPU frametimes.

**Comment by GT500org** [comment]
Out of curiosity, do you think that sort of information is something that an anti-cheat would even allow access to?

**Comment by Khalikul** [comment]
> Out of curiosity, do you think that sort of information is something that an anti-cheat would even allow access to?

Most of the games won't allow accessing that info I guess like in PUBG or Valorant - These anti-cheats won't allow- I may be wrong
