### ISSUE TITLE
App crash on start.

### ISSUE THREAD

**Issue by Nerboruto** [CXWorld/CapFrameX#212]
i was unable to resolve..
![1](https://user-images.githubusercontent.com/10599012/185758082-f63f28eb-6eed-4ae9-9166-ff7ebcf7d542.jpg)
![2](https://user-images.githubusercontent.com/10599012/185758085-6156107a-6ec4-4a1b-a974-4c5a453ccc0d.jpg)
![3](https://user-images.githubusercontent.com/10599012/185758087-bff0c24c-64f6-47d0-9b7b-7c1ae6effb79.jpg)

**Comment by DevTechProfile** [comment]
Try build no. 63.

https://archive.capframex.com/

**Comment by Nerboruto** [comment]
> Try build no. 63.
> 
> https://archive.capframex.com/

it gives the same errors... 

System.Runtime.InteropServices.SEHException
   in OpenHardwareMonitor.Hardware.CPU.GenericCPU.GetTimeStampCounterFrequency()
   in OpenHardwareMonitor.Hardware.CPU.GenericCPU.EstimateTimeStampCounterFrequency(Double ByRef, Double ByRef)
   in OpenHardwareMonitor.Hardware.CPU.GenericCPU..ctor(Int32, OpenHardwareMonitor.Hardware.CPU.CPUID[][], OpenHardwareMonitor.Hardware.ISettings)
   in OpenHardwareMonitor.Hardware.CPU.IntelCPU..ctor(Int32, OpenHardwareMonitor.Hardware.CPU.CPUID[][], OpenHardwareMonitor.Hardware.ISettings, CapFrameX.Monitoring.Contracts.ISensorConfig)
   in OpenHardwareMonitor.Hardware.CPU.CPUGroup..ctor(OpenHardwareMonitor.Hardware.ISettings, CapFrameX.Monitoring.Contracts.ISensorConfig)
   in OpenHardwareMonitor.Hardware.Computer.set_CPUEnabled(Boolean)
   in CapFrameX.Sensor.SensorService.<StartOpenHardwareMonitor>b__39_0()
   in System.Threading.Tasks.Task.Execute()
   in System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   in System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   in System.Threading.Tasks.Task.ExecuteWithThreadLocal(System.Threading.Tasks.Task ByRef)
   in System.Threading.Tasks.Task.ExecuteEntry(Boolean)
   in System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by DevTechProfile** [comment]
Please check C:\Program Files (x86)\CapFrameX. Does the folder include CapFrameX.Hwinfo.dll?

**Comment by Nerboruto** [comment]
Yes it is present, 11kb dll

**Comment by DevTechProfile** [comment]
OK, build no. 64: https://archive.capframex.com/

I am using now the default exception handling. QueryPerformanceCounter/QueryPerformanceFrequency exception were not handled by the old approach. 

But I have to say, the error is really weird. Do you have disabled any high precision timers on your machine?

**Comment by Nerboruto** [comment]
always the same 3 errors...
high precision timers enabled in device manager although strangely it says no driver loaded, but it is not marked with an exclamation point and I see at irq resources and memory range

**Comment by Nerboruto** [comment]
well i looked in the pc and i remembered that this was entered at startup ...
bcdedit /set disabledynamictick yes
bcdedit /set useplatformclock true
but for a very specific reason, the pc has overclocked system bus from 266 to 320mhz, 
if i remove it speed detection is inaccurate and it happens that in games or if i watch a movie with vlc the timing is wrong and you go to stuttering.

**Comment by DevTechProfile** [comment]
I have tought about the problem for a while. There is proper exception handling and error management in the code. Tbh, I don't know why CX crashes on your machine.

**Comment by Nerboruto** [comment]
I also tried it on another non-recent xeon e5450 pc and it crashes the same

**Comment by DevTechProfile** [comment]
What OS is installed on your machine? Do you use the CapFrameX installer or portable version?

**Comment by Nerboruto** [comment]
WINDOWS 10  10.0.19041.804 CORE 2 DUO
WINDOWS 10  10.0.19041.573 xeon

**Comment by Nerboruto** [comment]
i'm doing windows updates, let's see what happens.

**Comment by Nerboruto** [comment]
updated to win10 ver 10.0.19044.1288
same errors app crash...

**Comment by DevTechProfile** [comment]
I have an old Core2Duo here. Maybe I am gonna look at it next week.

**Comment by Nerboruto** [comment]
> bcdedit /set disabledynamictick yes
> bcdedit /set useplatformclock true

it is not that the problem removed does not change anything.

**Comment by Nerboruto** [comment]
I updated motherboard and processor with a xeon v3 haswell, and I hope it works for me now, otherwise it means that something I know is not working correctly ... today I will try it again.

**Comment by DevTechProfile** [comment]
Maybe you should try a fresh install.

**Comment by DevTechProfile** [comment]
Anything new on the issue here? Would like to close the it.

**Comment by Nerboruto** [comment]
no please, 
I still have to do the tests ...

**Comment by Nerboruto** [comment]
made several tests with the portable version, he started quietly saddles other machines. the problem is just specific to those old cpu. the OS has nothing to do with it.

**Comment by DevTechProfile** [comment]
I have a Core 2 Quad Q6600 here. Gonna check that. At the end a solution could be to disable sensor readings on such old CPUs.

**Comment by Nerboruto** [comment]
any news? i parked the old pc waiting for this software ...

**Comment by DevTechProfile** [comment]
Unfortunately, I had no time to check that issue on the  2 Quad Q6600. Because of very restricted time I won't check that further, sorry.
