### ISSUE TITLE
App crash on startup

### ISSUE THREAD

**Issue by Dominiquini** [CXWorld/CapFrameX#218]
When I try to start the application, it immediately crashs without any message! The crash generate a folder on "C:\ProgramData\Microsoft\Windows\WER\ReportArchive", but I'm unable to opened (no permission).
After that, I can't try agains without restarting the PC (BUG https://github.com/CXWorld/CapFrameX/issues/217).
* The application was working fine until some time ago. I don't know what I did, but now the program is completely broken! I tried to reinstall and even run the portable version, but nothing works!

App Version: 1.6.9.6
OS Version: Windows 10 x64

Thanks.

**Comment by Dominiquini** [comment]
The exact same problem persists on the new version (1.7.0)

Thanks.

**Comment by DevTechProfile** [comment]
Thanks for reporting. Please give us more info about the hardware you are using.

**Comment by Dominiquini** [comment]
OS: Windows 10 x64 Build 19045.2193
CPU: Intel Core i7 6700K
GPU: NVIDIA GeForce GTX 1060 6GB

What else can I inform to help with this bug?

Thanks.

**Comment by Dominiquini** [comment]
Any update on this bug?

Thanks.

**Comment by DevTechProfile** [comment]
There seems to be a problem with the CPU detection. It's hard to identify the problem without debugging the code.

**Comment by Dominiquini** [comment]
Is there anything I can do to help?

**Comment by DevTechProfile** [comment]
Have you checked the latest beta?

**Comment by Dominiquini** [comment]
> Have you checked the latest beta?
> 
> Download from here: https://github.com/CXWorld/CapFrameX/releases/tag/v1.7.2beta

It appears to be working fine now with this new version!

Thanks
