### ISSUE TITLE
CapFrameX's overlay won't run with Surgeon Simulator

### ISSUE THREAD

**Issue by Ulver84** [CXWorld/CapFrameX#230]
Hi, 

Surgeon Simulator doesn't enable the overlay. 

https://store.steampowered.com/app/233720/Surgeon_Simulator/

**Comment by Ulver84** [comment]
And for Civilization III 
https://store.steampowered.com/app/3910/Sid_Meiers_Civilization_III_Complete/

**Comment by Ulver84** [comment]
https://store.steampowered.com/app/15700/Oddworld_Abes_Oddysee/

This game as well.

**Comment by DevTechProfile** [comment]
Do Afterburner + RTSS show an overlay?

**Comment by Taxxor90** [comment]
Besides surgeon simulator, the rest of the games you've listed are 20+ years old, I'm not surprised RTSS can't hook onto them

**Comment by Ulver84** [comment]
Hi, I justed installed MSI afterburner (haven't used it in ages) and it doesn't work either, so I suppose this is an RTSS issue. Thanks for help, cheers.

**Comment by Taxxor90** [comment]
Okay, I've written a comment on the other issue that fits here aswell so I'll close this one without writing it again^^
