### ISSUE TITLE
CapFrameX doesn't start with "Could not load file or assembly 'CapFrameX.RTSSInterface.dll'" exception

### ISSUE THREAD

**Issue by dreambottle** [CXWorld/CapFrameX#232]
I am using version 1.7.0 portable. And when I start the app, nothing appears on the screen. The process remains alive and doesn't hard-crash, so the only way to close it is from process manager.

In `Documents\CapFrameX\Logs\CapFrameX.log`, there's the following exception:
```
System.IO.FileNotFoundException: Could not load file or assembly 'CapFrameX.RTSSInterface.dll' or one of its dependencies. The specified module could not be found.
    File name: 'CapFrameX.RTSSInterface.dll'
       at CapFrameX.Bootstrapper.ConfigureContainer()
       at Prism.DryIoc.DryIocBootstrapper.Run(Boolean runWithDefaultConfiguration)
       at CapFrameX.App.OnStartup(StartupEventArgs e) in D:\\Jenkins\\workspace\\CX-App_release_1.7.0\\source\\CapFrameX\\App.xaml.cs:line 50
       at System.Windows.Application.<.ctor>b__1_0(Object unused)
       at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
       at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

It goes without saying that the dll is present in the same dir as the executable. Its hashes match what's in the .zip. RTSS is also installed and works without issues with Afterburner.

Until recently, CapFrameX used to work alright and now it just doesn't. I am not sure what changed on my end.

**Comment by dreambottle** [comment]
I reinstalled: RTSS, Nvidia driver (with DDU cleanup), CFX itself (extracted from zip) - none of this helped.

**Comment by DevTechProfile** [comment]
Ok, I thinks some C++ libs are missing. Use the the installer from our website. It checks dependencies and installs them if needed.

**Comment by dreambottle** [comment]
You were right, I downloaded and installed VC runtime from [here](https://learn.microsoft.com/en-US/cpp/windows/latest-supported-vc-redist?view=msvc-170) and it started to work again. It probably got uninstalled when I was messing with chocolatey packages recently.

As a suggestion, perhaps you could mention this dependency somewhere near download links or have an explicit error in the app when VC redist is missing?

I am closing this as solved.

**Comment by DevTechProfile** [comment]
> As a suggestion, perhaps you could mention this dependency somewhere near download links or have an explicit error in the app when VC redist is missing?

Good idea!
