### ISSUE TITLE
UI clipping outside of screen

### ISSUE THREAD

**Issue by Skyblueborb** [CXWorld/CapFrameX#233]
The UI of CapFrameX is clipping outside of the screen as seen in the screenshot below (notably on the bottom and top right)
![image](https://user-images.githubusercontent.com/73354158/213674484-9d13c662-f582-440c-9a1b-daefb76bdec9.png)
The resolution I'm using is 1360x768, which is probably the culprit but if anything can be done on the application side I'd be grateful.

**Comment by Taxxor90** [comment]
Yeah the UI elementes were tuned to need a minimum window size of 1400x800.
I did a little bit of rearranging to only need 1360x740, which is the most I could do but it should be enough to fit on a 768p screen.

Try out[This version](https://archive.capframex.com/builds/release/1.7.1/22/6376cb9518047c9e604d9a5439a1526471ca1387_installer.zip)

**Comment by Skyblueborb** [comment]
Everything fits fine now, thanks!
![image](https://user-images.githubusercontent.com/73354158/213734867-d7fb0162-6b53-4a28-9c97-12ea61728efe.png)
