### ISSUE TITLE
Crash on exit with AMD GPU

### ISSUE THREAD

**Issue by DanRaj89** [CXWorld/CapFrameX#237]
Every once in a while CapFrameX 1.7.1 will crash on exit, sometimes the process will simply hang on exit forcing me to end it. Running latest AMD drivers 23.2.2 on a 6600XT, Windows 10.

Report from Reliability Monitor and attached a .dmp file

`Source
CapFrameX

Summary
Stopped working

Date
‎28.‎2.‎2023. 15:22

Status
Report sent

Description
Faulting Application Path:	C:\Program Files (x86)\CapFrameX\CapFrameX.exe

Problem signature
Problem Event Name:	APPCRASH
Application Name:	CapFrameX.exe
Application Version:	1.7.1.6
Application Timestamp:	63e0e525
Fault Module Name:	amdadlx64.dll
Fault Module Version:	31.0.14033.1012
Fault Module Timestamp:	63efbec6
Exception Code:	c0000005
Exception Offset:	000000000008fe04
OS Version:	10.0.19045.2.0.0.256.121
Locale ID:	9242
Additional Information 1:	3644
Additional Information 2:	3644f935d72b618867a898a6bcd6dd5d
Additional Information 3:	2001
Additional Information 4:	2001c6989838056e6f167100623fad15

Extra information about the problem
Bucket ID:	a4605e9971ca3e91e9bc3172db8264c9 (1854411515948590281)
`
[CapFrameX.exe.4256.dmp.zip](https://github.com/CXWorld/CapFrameX/files/10851251/CapFrameX.exe.4256.dmp.zip)

**Comment by DevTechProfile** [comment]
Will check that later.

**Comment by DevTechProfile** [comment]
I've checked the RX 6800 XT with latest driver. No issues here on my side but I noticed, that the driver now supports ALDX with RDNA2. So I think it's important to do a clean install. Use DDU to uninstall the old driver.

**Comment by DanRaj89** [comment]
Thanks for looking into it. I've already used DDU before installing this version of the driver. Unfortunately, the issue is so sporadic that I don't know if I'll be able to narrow it down. 

Two things that come to mind:
-I'm always running HWInfo in the background so there might be some conflict there.
-My GPU is OCed, however it's stable in absolutely everything I've played/tested, around 10+ games stress tests. I doubt it's the cause, but worth noting.

**Comment by DevTechProfile** [comment]
Please send the log files in MyDocuments\CapFrameX\Logs to contact@capframex.com

**Comment by DanRaj89** [comment]
Sent

**Comment by DanRaj89** [comment]
I've experienced a hang on close, CapFrameX will remain in memory with a single thread CapFrameX.exe!RemoveIcon. Attached screenshot.
I have created a dump of the hung process, can send you if necessary (164MB)
![Screenshot 2023-03-11 030358](https://user-images.githubusercontent.com/54473533/224459477-1435258d-770f-4c6a-9489-430f969aad09.png)

**Comment by DevTechProfile** [comment]
I am not able to repeat the error on my system using an RX 6800 XT and the same driver.
