### ISSUE TITLE
GPU TBP Sim not anymore available for AMD graphics card since 1.7.1

### ISSUE THREAD

**Issue by octra** [CXWorld/CapFrameX#238]
Since 1.7.1 I have no enty anymore for GPU TBP Sim on a 6900 XT graphics card. When I open 1.7.0 it's there. Already deleted all app config files but the issue persists.

Might this be some kind of regression since 1.7.1 introduced GPU TBP Sim for Intel cards?

**Comment by DevTechProfile** [comment]
You can force an ADL fallback with the latest build. The fallback provides TBP Sim. 

Download (build no. >=14): https://archive.capframex.com/

![image](https://user-images.githubusercontent.com/30285858/226726718-846111ab-b642-4716-98c6-c8b30f58488a.png)
