### ISSUE TITLE
incorrect frequency display on ryzen 5600 and missing some metrics on 5700 xt

### ISSUE THREAD

**Issue by linyarx** [CXWorld/CapFrameX#239]
1) the frequency is displayed incorrectly on the ryzen 5600. The processor is overclocked to 4850 MHz, but in the metrics it shows 4800, that is, 50 MHz less. In this case, if you put 4800 and below, it will be displayed correctly. It looks like some kind of limit.
2) 2) a lot of metrics on the 5700 xt video card are missing: memory voltage, vrm temperature, etc. The msi afterburner patch notes described the same problem. I think this is a conflict between drivers or windows with monitoring programs

**Comment by linyarx** [comment]
[CapFrameX.log](https://github.com/CXWorld/CapFrameX/files/10931342/CapFrameX.log)

**Comment by DevTechProfile** [comment]
Ok, you have installed the latest beta, that's good. The log file telling me that RDNA1 is now supported by ADLX lib which means that memory voltage and VRM temperatures for example are not supported any longer. 

Our frequency detection is based on the latest PPR for AMD Family 19h Model 01h. I am afraid there is nothing we can do unless we will switch over to Ryzen SMU.

**Comment by linyarx** [comment]
ok, thx for reply

**Comment by linyarx** [comment]
And the last question, can you somehow embed these sensors in the overlay? Maybe take them from somewhere else? it’s just that these are critical indicators and I don’t understand at all how they could be removed in the new version of the libraries
