### ISSUE TITLE
[FEATREQ] Instead of hard affinity - would it be possible to use CPU sets instead (or as an alternative) ?

### ISSUE THREAD

**Issue by msoltyspl** [CXWorld/CapFrameX#241]
Hi,

Having peeked over Process Lasso's features - it has support for cpu sets which give more flexible control over the cpu assignment than hard affinity. Would that be a viable option/feature for CFX ?

https://bitsum.com/processlasso-docs/#cpu-sets
https://learn.microsoft.com/en-us/windows/win32/procthread/cpu-sets

**Comment by msoltyspl** [comment]
Hmmm, having quickly tested that on my 3900x with cb20 (set to 8 rendering threads) and with that lasso tool (created set for 4 cpus) - "the golden goose" I though that feature would be turned out not so great - it literally behaved like hard affinity (unless I was doing something wrong).

**Comment by DevTechProfile** [comment]
Thanks for suggesting features. I think this a very specific threading/affinity feature and therefore out of scope for CapFrameX. Tbh, I am actually thinking about to remove the Thread Affinity Controller and create another app providing such features. Not sure yet...

**Comment by msoltyspl** [comment]
> Tbh, I am actually thinking about to remove the Thread Affinity Controller and create another app providing such features. Not sure yet...

This might be pretty neat actually - something simple where one could setup hard and "soft" affinity on a per-app basis. Perhaps some other stuff would also be possible - such as letting users set preferred core ranking (though that one is I think possible only globally, maybe one day though ...)
