### ISSUE TITLE
GPU temperature not always visible.

### ISSUE THREAD

**Issue by Magniflex99** [CXWorld/CapFrameX#242]
Platform: Notebook Asus Rog G532LWS, Windows 11 Home, 10th generation Intel, Rtx 2070 Super, all drivers and applications updated to the latest stable version available. I would like to report a problem: the GPU temperature often is not displayed, but only in some rare cases it can be seen. Even in the configuration of the data to be displayed in the overlay, I can't find it, but only the Hotspot temperatures... I hope it's just my problem, but in fact, it's the only setting that I haven't been able to customize (the color I mean).
![PXL_20230324_215724605.jpg](https://user-images.githubusercontent.com/121835112/228229703-4d99c15f-dccd-4251-aff0-820915d9b94b.jpg)

**Comment by DevTechProfile** [comment]
Thanks for reporting. What about other tools? Do HWiNFO or Afterburner display the sensor always correctly?

**Comment by Magniflex99** [comment]
> Grazie per la segnalazione. E gli altri strumenti? HWiNFO o Afterburner visualizzano sempre correttamente il sensore?

Yes, GPU temperature is reported on HWiNFO64. Currently I do not have Afterburner installed.

https://user-images.githubusercontent.com/121835112/228276153-1008ba51-0ba3-4da0-89f3-326023dd7687.mp4

**Comment by DevTechProfile** [comment]
Please install build no 21 and send me the latest log file in MyDocuments\CapFrameX\Logs.

Download: https://archive.capframex.com/

Post the log file here or send it to contact@capframex.com.

**Comment by Magniflex99** [comment]
> Please install build no 21 and send me the latest log file in MyDocuments\CapFrameX\Logs.
> 
> Download: https://archive.capframex.com/
> 
> Post the log file here or send it to contact@capframex.com.

How could I backup the configuration of the current version I'm using? (1.7.1)

**Comment by DevTechProfile** [comment]
Configs are untouched when uptating CapFrameX

**Comment by Magniflex99** [comment]
> Le configurazioni non vengono modificate durante l'aggiornamento di CapFrameX

Ah okay, I didn't know that. I've been using CapFrameX for the first time for a few days now. Installed build no. 21. It has the same problem in my setup.
[CapFrameX.log](https://github.com/CXWorld/CapFrameX/files/11093061/CapFrameX.log)

**Comment by DevTechProfile** [comment]
The log file doesn't include entries from the 1.7.2 beta. Can you please upload the right file?

**Comment by Magniflex99** [comment]
> Il file di registro non include le voci della versione beta 1.7.2. Puoi per favore caricare il file giusto?

Excuse me, I took the log, right after installing 1.7.2, and running it. The log file that I attach below, has the time and date of creation, the last time I started CapFrameX, I hope it's fine now...

[CapFrameX.log](https://github.com/CXWorld/CapFrameX/files/11093372/CapFrameX.log)

**Comment by DevTechProfile** [comment]
I am in contact with Nvidia on this issue.

**Comment by Magniflex99** [comment]
> Sono in contatto con Nvidia su questo problema.

Well! I hope it is not too complicated to solve, and there is also on their side, the same commitment.

**Comment by DevTechProfile** [comment]
No bug is unfortunately not reproducible. All CX sensor working well on Laptop with RTX A2000.
