### ISSUE TITLE
Dear developer, can you provide a Chinese

### ISSUE THREAD

**Issue by newchin** [CXWorld/CapFrameX#247]
Dear developer, can you provide a Chinese translation for your software? Thank you. If you are a fan of your Chinese environment and have a Chinese translation on Steam, it would be great

**Comment by newchin** [comment]
Oh, please forgive my mechanical translation that was not smooth, but as a Chinese player who doesn't understand English, I really hope you can quit Chinese translation. After all, my English proficiency is as rotten as a rotten tomato that has been in use for more than ten days.

**Comment by DevTechProfile** [comment]
As an Open Source project, and especially non-profit, the effort would be far too high. English is considered the international standard.
