### ISSUE TITLE
Feature Request: Add "Time in GPU load limit (%)" as a selectable metric in the Comparison tab

### ISSUE THREAD

**Issue by PatrikTheToth** [CXWorld/CapFrameX#249]
Hello, 

I love the software, amazing work!

One thing I would like to see a selectable metric on the comparison page where I can see basically the extent of the GPU limit for each performance capture. The Statistics tab already reports an average "Time in GPU load limit (%)" metric, which I think would be perfect. 

Thank you for considering and have a great day!

**Comment by Taxxor90** [comment]
As this is a percentage and not an FPS metric, there is currently no way to effecitvely add it to the comparison tab.

**Comment by DevTechProfile** [comment]
The comparison page would need a deep rework to able to provide such a feature. 

The software is now in maintenance mode, no new features.
