### ISSUE TITLE
rockstar launcher cannot be added to ignore list

### ISSUE THREAD

**Issue by patrickrabaja** [CXWorld/CapFrameX#252]
rockstar launcher cannot be added to ignore list

![image](https://github.com/CXWorld/CapFrameX/assets/61625031/12c7389b-68e9-49f6-b381-a81bfa306489)
![image](https://github.com/CXWorld/CapFrameX/assets/61625031/760b6b04-36e7-4c7c-a96e-299793c0159e)

**Comment by Taxxor90** [comment]
Why would you want to add it to the ignore list? That list is for processes that get falsely detected by the capture service .

If its about the overlay, that has nothing to do with our capture service and is dependend on your RTSS settings.
