### ISSUE TITLE
how does CapFrameX detects games?

### ISSUE THREAD

**Issue by hedihadi** [CXWorld/CapFrameX#253]
i don't have CPP or C# knowledge so i can't really check that from the source code, how does this program detects the running processes? how it can differentiate between a game process and a normal process? thank you

**Comment by Taxxor90** [comment]
Like OCAT or Frameview, we're using PresentMon to detect and capture processes.

How does PResentMon differentiate between a game and a normal process? That would be a question for the PresentMon team. I believe they have some sort of internal filter on if a process is using the GPU in any form but as I said, better ask them directly.

As for our own software, we just have a blacklist of processes that still can get detected by PresentMon and are not games, the list that you see on the capture page.

**Comment by hedihadi** [comment]
@Taxxor90 ah my bad, i thought Presentmon mandatorily asks you for a process name, but if i don't write any process name, it will automatically finds any running games, that's great to know!
