### ISSUE TITLE
Troubleshooting CapFrameX Overlay Issues on Windows 11 with RTX 3090

### ISSUE THREAD

**Issue by ronyn77** [CXWorld/CapFrameX#254]
Hello,

I am writing here in the hope of finding a solution to my problem. I have been using MSI Afterburner for many years, and it has always worked well. However, it suddenly stopped working, and I am not sure if this coincided with when I changed my TV to a new one. I now have a Samsung S95C, which supports VRR and 144Hz (previously, with my LG C8, I was limited to 4K60Hz). I have made several attempts to solve the problem, but nothing has helped. On the other hand, the Nvidia overlay works as intended.

As a troubleshooting step, I decided to uninstall RivaTuner and MSI Afterburner, and I also deleted all the related registry keys using a specialized application for that purpose. I then decided to try CapFrameX, which also relies on RivaTuner Statistics Server. After installing both programs, I enabled the overlay in CapFrameX, but once again, it does not display anything while a game is running.

Could you please assist me in troubleshooting this problem? I am using Windows 11, updated with the latest updates, and my video card is an RTX 3090.

**Comment by DevTechProfile** [comment]
Please post screenshots of the CapFrameX overlay tab and the RTSS UI.

**Comment by ronyn77** [comment]
Here it is : 
![Snag_a9a89](https://github.com/CXWorld/CapFrameX/assets/22024600/957a5948-3dc1-4674-b287-215ac144eeee)
And this is when I open the plugin, which I think is responsible for the on-screen display.
![Snag_ed50e](https://github.com/CXWorld/CapFrameX/assets/22024600/7d55dee3-3346-4f2e-b00a-1e2ab41a0da0)

**Comment by DevTechProfile** [comment]
What games did you test? RTSS can have problems with Vulkan games.

**Comment by ronyn77** [comment]
God of War, Fallout 76, Red dead online, horizon zero dawn, cyberpunk 2077, Forza Horizon 5, Mortal Kombat 11, Tom clancy's the division 2, Dragonball Fighter Z, Watch Dogs Legion and others....

**Comment by DevTechProfile** [comment]
Ok, try the latest RTSS beta: https://forums.guru3d.com/threads/msi-ab-rtss-development-news-thread.412822/page-207#post-6163298

**Comment by ronyn77** [comment]
Thank you for the suggestion. Things seem to be improving; however, the only remaining issue is that the framerate still shows as zero. On the other hand, when using MSI Afterburner, it displays the correct FPS.
<img width="944" alt="Snag_f07d411" src="https://github.com/CXWorld/CapFrameX/assets/22024600/c6147917-3244-4aa0-a8eb-4a9d5a8dcd10">

**Comment by DevTechProfile** [comment]
Yes, that's because multiple processes are being detected. Check the process list and put the process that isn't a game on the ignore list.

**Comment by ronyn77** [comment]
Thank you very much for your effort! You solved the problem!
