### ISSUE TITLE
Invalid voltage readings reported in both overlay and captures

### ISSUE THREAD

**Issue by ghost** [CXWorld/CapFrameX#263]
Both the overlay and capture functions are recording all CPU related voltages as 1.55v on my system. Confirmed with hwinfo and the correct voltages show up there.

Both core and SoC voltages are effected. GPU voltages are unaffected.

System specs are in the attached image.

![capture](https://github.com/CXWorld/CapFrameX/assets/150945031/70392d9c-53da-48d7-8f71-2ac3dd0f6cc2)

**Comment by chaosmaou** [comment]
This issue appears to be caused by Windows Memory Integrity.
I ended up turning the feature off and then CapFrameX is able to capture a lot more data.

**Comment by DevTechProfile** [comment]
What CapFrameX version is this?

**Comment by chaosmaou** [comment]
I tried both 1.7.1 and the 1.7.2 pre-release and both had the same issue.

**Comment by chaosmaou** [comment]
Interestingly each version behaves a bit different. In 1.7.1, voltages show up as all 1.55v. In the 1.7.2 pre-release, they all show up as 0.00v. 

In both CPU MHz is shown as 0MHz.

**Comment by DevTechProfile** [comment]
Actually, the v1.7.2 beta got a Ryzen voltage bug fix. If the Memory Integrity causing this, there is nothing what we can do from our side. The effort would be extremely high (redesign of some of the core components from scratch).
