### ISSUE TITLE
Moving a Running Process to the Ignore List via Command Line or File Modification

### ISSUE THREAD

**Issue by DineshKrishnan1718** [CXWorld/CapFrameX#265]
Hello Team,

I'm attempting to relocate the Windows Terminal to the ignore list by adding the process to the process.JSON file. However, it doesn't seem to be shifting to the ignore list successfully. 

![image](https://github.com/CXWorld/CapFrameX/assets/137282180/b722fc14-6273-48c5-be4e-26d00be42236)

Could you please guide me on how to achieve this without manual intervention, perhaps through a command-line approach or by modifying a file directly? I appreciate your assistance.

**Comment by Taxxor90** [comment]
Eh, why don't you just click on the button to add it?

**Comment by DevTechProfile** [comment]
As @Taxxor90 already mentioned, please use the standard features for that concern.
