### ISSUE TITLE
need to move some process in process list to ignore list

### ISSUE THREAD

**Issue by malay190** [CXWorld/CapFrameX#266]
working some gaming automation project by using capframex tool 
I need to move some process to ignore list 
List of process: notepad , XboxGameBarWidgets 
I need a command line or file change solution not doing manually click ignore button 
referred #265  issue but it couldn't resolve.
can you please help guide me solution

**Comment by Taxxor90** [comment]
I gave you the file change solution in the last iussue

{
"Name": "XXXXXX",
"DisplayName": null,
"IsBlacklisted": true,
"LastCaptureTime": null
},

After a change to the file, you of course need to restart the app.

The used processes.json is located either in documents if you're using the official beta version or in AppData/Roaming if you're using one of the latest builds,
