### ISSUE TITLE
Would be possible to read AFMF with the latest AMD driver?

### ISSUE THREAD

**Issue by mirko8054** [CXWorld/CapFrameX#268]
As title says, is it possible?

**Comment by Taxxor90** [comment]
Not possible at this point. AMDs driver team is notified that we'd like to be able to do this

**Comment by mirko8054** [comment]
I understand, what can you tell me about TGP sensor not working on the latest version? Was it changed too?

**Comment by Taxxor90** [comment]
https://archive.capframex.com/builds/release/1.7.3/7/a383842cb3172af58b40687e26a2c3a9d1d9e74b_installer.zip

This one should fix the TBP error

**Comment by mirko8054** [comment]
Yes it did, thank you.
