### ISSUE TITLE
Minimize CX window to the system tray function stopped working after installing CX v.1.7.2

### ISSUE THREAD

**Issue by RodroG-85** [CXWorld/CapFrameX#269]
After installing the latest CapFrameX 1.7.2 release build, minimizing the program window to the Windows system tray is not possible anymore.

Once the program window is opened/shown, only minimizing into the taskbar is allowed using the Minimize window button. So, now, the CapFrameX program (processes) cannot run in the background when minimized once the window has been opened or shown.

However, the minimize to the system tray function still works the first time you launch CX (before opening/showing the program window for the first time after launch) on 1.7.2 when the "Start minimized" APP setting is enabled.

Could you restore the minimizing to the system tray behavior or (re)implement the function once the application window is opened or shown?

Best regards.

**Comment by mirko8054** [comment]
Can confirm, also another issue: CapframeX does not catch up the Total board power sensor anymore, on AMD gpu in latest drivers: 24.1.1. It was working in 1.7.2 beta as i ran that for months.

**Comment by Taxxor90** [comment]
A function was removed that seemed to be neccessary for the way the minimize to tray method was implemented

[1.7.3 beta](https://archive.capframex.com/builds/release/1.7.3/3/7532705b51e2dd6ac80822e7090d7b2ec1758b51_installer.zip) adds another way of doing this

**Comment by RodroG-85** [comment]
That was fast! Thank you @Taxxor90
