### ISSUE TITLE
Suggestions on language

### ISSUE THREAD

**Issue by StarSky8899** [CXWorld/CapFrameX#270]
### DISCLAIMER:  This passage was translated with a translation tool, it may be strange? Sorry I'm not know how to speak English...

**Thank you for the software, he really works well, but I don't read English very well, so I thought it would provide an easy way to change the language, if that would be a pain in the ass forget it**

**_good luck!_**

**Comment by DevTechProfile** [comment]
CapFrameX is an international tool, thus English is the way to go. We have no plans to support other languages.
