### ISSUE TITLE
add process to ignore list after closing 

### ISSUE THREAD

**Issue by PG248** [CXWorld/CapFrameX#273]
If have the problem that some games open another app for displaying video behind the scenes. CapFrameX then refuses to start a capture with the multiple processes detected error.
The game runs in full screen mode so I cannot select the second process and choose ignore because I don't see the CapFrameX UI. When I quit the game I see both processes for a fraction of a second in CapFrameX process list but they vanish before I have a chance to select one and send it to the ignore list.
Would it be possible to set a timeout before the list gets updated? Or is there another way to put the second process on the ignore list?

**Comment by Taxxor90** [comment]
Well the easiest way would be to tab out of the game(or start it in window mode) to remove the unwanted process
