### ISSUE TITLE
I used the i9 13900K ES2 and after pressing F11, the in-game detection chart control disappeared

### ISSUE THREAD

**Issue by pamQWQ** [CXWorld/CapFrameX#274]
I used the i9 13900K ES2 and after pressing F11, the in-game detection chart control disappeared. After pressing F11 again, the chart control displayed normally again, which is a bug. I am using Win11 professional workstation version 23H2, detailed system version 22631.3447  Software versions 1.7.1 and 1.7.2

**Comment by pamQWQ** [comment]
> “游戏内检测图表控制”你指的是叠加层吗？如果是这样，不，这不是一个错误，应该在基准测试期间停用它，以免影响游戏性能。您可以在覆盖选项中禁用该行为

Press F11 to capture game frames, but before pressing it, OSDFPS displays CPU usage and GPU usage under normal conditions. After actually pressing it, everything displayed in RTSS will disappear. After pressing it again, the recovery usage rate, etc. will be displayed on the screen normally. On my old computer, it can be displayed all the time. I don’t know what the problem is.

**Comment by Taxxor90** [comment]
> I don’t know what the problem is.

I just told you, RTSS is intended to dissapear by default when pressing the capture hotkey. If you don't want that behaviour, disable it in the "OSD options" on the Overlay page.
![image](https://github.com/CXWorld/CapFrameX/assets/45570250/a75d60ef-f456-4a6f-83e4-419f4c329e75)

**Comment by pamQWQ** [comment]
> > 我不知道问题是什么。
> 
> 我刚刚告诉过你，当按下捕获热键时，RTSS 默认会消失。如果您不希望出现这种行为，请在叠加页面上的“OSD 选项”中将其禁用。很可能该选项已在您的旧计算机的配置中被禁用 ![图像](https://private-user-images.githubusercontent.com/45570250/324864755-a75d60ef-f456-4a6f-83e4-419f4c329e75.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4ODI4MDgsIm5iZiI6MTcxMzg4MjUwOCwicGF0aCI6Ii80NTU3MDI1MC8zMjQ4NjQ3NTUtYTc1ZDYwZWYtZjQ1Ni00YTZmLTgzZTQtNDE5ZjRjMzI5ZTc1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIzVDE0MjgyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhYjFhZmJhNTkwNDgzNDIwZTUxYjg5MWMzODdjZjcyMjMwNzM5ZTdjMWU4NTk4MmE2NDAyZTAzNzUzY2YwMTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KfbTwmTQRIIJLurde1aPJ49frutEjgTI3QTZPGHKQME)

OK OK I didn’t understand the meaning at first until you posted the picture. I am Chinese. Embarrassed. Thank you for your answer.
