### ISSUE TITLE
User ignore list problem

### ISSUE THREAD

**Issue by ODDda** [CXWorld/CapFrameX#276]
I don't know if this was mentioned before, but CapFrameX has some problem with adding imageglass to the ignored list. 
Even after it was added, it still shows on image:

<details>

<img src="https://github.com/CXWorld/CapFrameX/assets/56647606/0dfafe7a-e149-49ae-82c2-40b0963521e3">

</details>

Or there is some problem with my version of the program, it seems that whatever I'm adding to this list it's ignored, I mean overlay is still active. It seems as that CapFrameX is ignoring my process ignored list, but installation(default) list is respected.

**Comment by Taxxor90** [comment]
https://www.capframex.com/support

> The overlay shows on applications although they are on my ignore list
> The process ignore list only affects the Presentmon capture service. On what applications the overlay is shown is controlled by RTSS itself because it's completely independend and we can only control what it shows, not where it does this.
> 
> If you want RTSS to not show the overlay on a specific application, you can create a new profile within RTSS, select the wanted process and then disable "On-Screen Display support" for that profile.
