### ISSUE TITLE
Vulkan Overlay not displayed

### ISSUE THREAD

**Issue by iNgeon** [CXWorld/CapFrameX#278]
Star Citizen recently added Vulkan.
When running the game on Directx11 the overlay is displayed.
When swapping to Vulkan, the overlay dissapears. When hitting the print screen button it shows for a brief moment. When swapping back and relogging to DirectX11 overlay displays again.
Have tried uninstalling and reinstalling the latest RivaTuner Statistics Server v7.3.6
Deleted and redownloaded latest CapeFrameX
Tried Resync.
As per below, with Overlay active it only shows on DirectX11
- [DxDiag.txt](https://github.com/CXWorld/CapFrameX/files/15402216/DxDiag.txt)

![xxssFxNVIu](https://github.com/CXWorld/CapFrameX/assets/3817692/bc72e8f5-9f12-490a-8e4b-65813b3ef0d0)
![KultxG5lGw](https://github.com/CXWorld/CapFrameX/assets/3817692/fd02542b-ac6b-4b3b-950e-9412f8e31f02)
![2024-05-22_11-18-19-406_CapFrameX_ZoRanivqZu](https://github.com/CXWorld/CapFrameX/assets/3817692/c89827aa-29eb-43ac-b64d-bf7f3a67aa90)

**Comment by Taxxor90** [comment]
That's a problem on RTSS end, not ours
