### ISSUE TITLE
wrong framerate display

### ISSUE THREAD

**Issue by 2607627233** [CXWorld/CapFrameX#280]
![20240609174306_1](https://github.com/CXWorld/CapFrameX/assets/43110396/3031852b-c57a-47a6-948e-3fba0ae44198)
graph was right
and sometimes it display 0 fps

**Comment by Taxxor90** [comment]
It will display 0 FPS when you have none ore more than 1 process detected in your running processes list.

The values from the FPS graph come directly from RTSS, the standard FPS value at the top first is evaluated by CapFrameX.

From the looks of it, you seem to have another application running that is detected by CapFrameX and that's running at 30FPS while the graph schows you the value of the game that's currently in the foreground

**Comment by 2607627233** [comment]
> 当您在正在运行的进程列表中没有检测到任何进程或超过1个进程时，它通常应显示0 FPS。
> 
> FPS 图中的值直接来自 RTSS，CapFrameX 首先根据正在运行的进程列表中的选定进程评估顶部的标准 FPS 值。
> 
> 从外观上看，您似乎在屏幕截图中检测到的应用程序之前启动了另一个应用程序，该应用程序由 CapFrameX 检测到并以 30FPS 运行，而图表显示当前处于前台的游戏的价值。
> 
> 该列表中应该只有一个进程，如果有多个进程，则必须选择所需的进程 ![图像](https://private-user-images.githubusercontent.com/45570250/337969289-5f732fa2-5ca2-4f12-a70d-2dafc5410c51.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5ODk3NDMsIm5iZiI6MTcxNzk4OTQ0MywicGF0aCI6Ii80NTU3MDI1MC8zMzc5NjkyODktNWY3MzJmYTItNWNhMi00ZjEyLWE3MGQtMmRhZmM1NDEwYzUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEwVDAzMTcyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVkODBmYzE2MmY1YjQ5ZTRlMzI3ZDNiOGRiOTZmNmZmMjk1NzA4NDcxNTdiMzkwODMyOTliYjk5YTdlYjg4NjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.JP9-7Vozcn5EMPIaIK31WsV2TNp4pJFkY4x05GT5QZ8)
> 
> 编辑：我刚刚发现了一个问题，即使有多个进程（只要您没有手动选择一个进程），该列表中的第一个进程也始终显示 FPS，所以我坚信这是您的问题。如果我是对的，当您检测到多个进程时，此版本应始终显示 0FPS https://archive.capframex.com/builds/release/1.7.3/19/6c0e0d1576a51c34f9508bfb3362ef1c7502a2e4_installer.zip

thanks
