### ISSUE TITLE
Help with PMD Metrics, RDNA3

### ISSUE THREAD

**Issue by NeilTohno** [CXWorld/CapFrameX#286]
![1](https://github.com/user-attachments/assets/13b947df-1ba4-444a-a2ff-215d19983857)

![2](https://github.com/user-attachments/assets/b34d2bdf-4c8c-49ea-8b69-994aa687527e)

I found  the program has not showing any value on my computer system, PMD Metrics.
And please tell me how to import these GPU related values ​​from HWinfo (or LibreHardwareMonitor), thanks.

CapFrameX  version : 1.7.4.1
[CapFrameX_log.zip](https://github.com/user-attachments/files/17299759/CapFrameX_log.zip)

**Comment by Taxxor90** [comment]
You need a [Powernetics V2](https://www.cybenetics.com/index.php?option=powenetics) to use the PMD option

**Comment by NeilTohno** [comment]
> You need a [Powernetics V2](https://www.cybenetics.com/index.php?option=powenetics) to use the PMD option

Is there other way to import GPU related values (as I said before) to CapFrameX？Thank you.

**Comment by Taxxor90** [comment]
No, only the sensors provided by CX itself

**Comment by NeilTohno** [comment]
> No, only the sensors provided by CX itself

Thanks for your response.
