### ISSUE TITLE
Unable to display lunarlake sensor readings

### ISSUE THREAD

**Issue by plainround** [CXWorld/CapFrameX#288]
Unable to display lunarlake sensor readings, frames can be displayed correctly on overlay but not sensor.
In my desktop there are a lot of parameters in this tab, but in the laptop it's blank here.
Also I made some attempts like checking tbp and adl and it didn't work.
![snap3441](https://github.com/user-attachments/assets/41ac6014-3329-477c-9020-0d7862e43f51)

**Comment by DevTechProfile** [comment]
Thanks for reporting. I will implement Lunar Lake soon. Intel is going to send me laptop within the next 2 weeks hopefully.
