### ISSUE TITLE
Can´t import overlay templates

### ISSUE THREAD

**Issue by RI0lopas** [CXWorld/CapFrameX#291]
Hi, i can´t seem to get capframex to save custom overlay templates,; first i didn´t have the configuration folder in my documents, then once i had it i tried copy pasting the files to this folder, but as soon as i restart capframex the files .Json, disappear from the configuration folder.

sorry for my english.

thank you

**Comment by DevTechProfile** [comment]
You can also type %appdata%\CapFrameX in the Windows Explorer navigation bar. This is the new location for CX configs as already stated by @Taxxor90.
