### ISSUE TITLE
ADL fallback not loading GPU sensors in v1.7.4 beta

### ISSUE THREAD

**Issue by Dendari92** [CXWorld/CapFrameX#292]
Hello.
In the new 1.7.4 beta version (downloaded from github releases page) when the "Use ADL fallback if available" option is checked no GPU sensor is available in CapFrameX.
![image](https://github.com/user-attachments/assets/2ae64f92-5d54-48e0-86e6-1e4e21a430df)
Unchecking the option will show the GPU sensors no problem.
![image](https://github.com/user-attachments/assets/4c3f881c-73f4-401e-ab1d-9ebb026c4a34)

My GPU is AMD Radeon RX 6800 XT and I'm using the 24.10.1 driver (released very recently).
I did a rollback to the 1.7.3 beta version available in the github releases page and the problem is not present.
I'm mostly using that option for the TBP Sim sensor so it's not a big deal.

I'm attaching some log files:
[CapFrameX_1.7.4.1_ADL.log](https://github.com/user-attachments/files/17446319/CapFrameX_1.7.4.1_ADL.log)
[CapFrameX_1.7.4.1_ADLX.log](https://github.com/user-attachments/files/17446318/CapFrameX_1.7.4.1_ADLX.log)
[CapFrameX_1.7.3.4_ADL.log](https://github.com/user-attachments/files/17446320/CapFrameX_1.7.3.4_ADL.log)

**Comment by DevTechProfile** [comment]
I've removed the ADL fallback option because ADL2 API is no longer supported by the latest Adrenalin driver.

We will implement a TBP Sim sensor for RDNA2 cards.

**Comment by DevTechProfile** [comment]
TBP Sim with ADLX and RX 6800 XT. 

Download build #14: https://archive.capframex.com/ 

![image](https://github.com/user-attachments/assets/e6113c07-186d-484b-9230-a87c031d67c1)

**Comment by Dendari92** [comment]
Thanks, I've updated to 1.7.4 beta build 14 and I can confirm TBP sim is working without ADL fallback! 😁
