### ISSUE TITLE
1.7.4 beta - missing application latency and sync tab

### ISSUE THREAD

**Issue by georgi-iovchev** [CXWorld/CapFrameX#294]
There is no more application latency metric reported (in report and in overlay) in 1.7.4 beta and also there is no more "SYNC" tab used for input lag analysis.
I guess this is on purpose. Are there any plans to reintroduce those ?

**Comment by DevTechProfile** [comment]
I've disabled the entire feature. At the end, the app latency metric wasn't accurate enough. It was actually really bad in some cases. I don't want to maintain something that doesn't meet my quality standards.

**Comment by ininsicken** [comment]
Doesn't CapFrameX use PresentMon? I was using PresentMon for it's ClickToPhoton measurement to measure input latency and it's great but I'm not a fan of how limited PresentMon. Any chance of adding this in the future? I really love CapFrameX but input latency is so important to me when benchmarking.
