### ISSUE TITLE
Please add 0.1% Lows to the Overlay, they are already implemented in Analysis

### ISSUE THREAD

**Issue by Vv-82** [CXWorld/CapFrameX#295]
I think it's a detriment to your software to not have them regardless how you feel about the 0.1% Lows because all other telemetry software have them in the OSD. People should have the option to use that if they want.

If I want to make a benchmark comparison between a CFX vs RTSS in a actual gamplay run for 0.1% Lows I can't, because CFX does not have that.

**Comment by DevTechProfile** [comment]
Implemented and published soon. 

![image](https://github.com/user-attachments/assets/ba636e76-4691-4837-b7e8-498814aca328)
