### ISSUE TITLE
Feature Request: Set a custom benchmark period per executable.

### ISSUE THREAD

**Issue by CMDMC12** [CXWorld/CapFrameX#61]
So for example if I'm running Batman: Arkham Knight, I can set a runtime of 1:34 (I think that's the right timespan) specifically for that game and the program will remember it for the next time I want to run it.

**Comment by DevTechProfile** [comment]
Possible way of implementation:


- add a save button next to capture time box when any process is selected(Tooltip: save capture time for this process)

- on button press, "process.exe=n" gets saved into a new textfile in Resources(CustomProcessCaptureTime.txt)

-anytime a process is detected that's present in that file, the capture time is set to n

**Comment by Taxxor90** [comment]
Possible way of implementation:

- add a save button next to capture time box when any process is selected(Tooltip: save capture time for this process)
- on button press, "process.exe=n" gets saved into a new textfile in Resources(CustomProcessCaptureTime.txt)
- anytime a process is detected that's present in that file, the capture time is set to n

**Comment by DevTechProfile** [comment]
What if a user wants to have a global behaviour? Do I have to reset the capture time each time a new game is detected?

**Comment by Taxxor90** [comment]
Hmmm, a toggle button to switch between global and explicit? That way the save button wouldn't be neccessary and the capture time would be written into the file when you start a capture and set when that process occurs again as long as the toggle is active.

**Comment by Taxxor90** [comment]
Alternative: Always write the last used capture times for each process in a textfile and just add a button next to the textbox to set it to the last used capture time for that process.

This would be the easiest way of implementation I think

**Comment by CMDMC12** [comment]
I was thinking maybe add in a new hotkey to use the time setting. That way even if you have a time period defined for a game, you can easily still just run it constantly if you want. 

I use CTRL + SHIFT + R now to start testing, and would probably assign CTRL + SHIFT + T to use a predefined time.

**Comment by Taxxor90** [comment]
Hmm but then we need to add another capture time box and we wnted the capture page to be as lightweight as possible

**Comment by DevTechProfile** [comment]
* Capture time is rather a dynamic setting
* The settingcan be operated very quickly

Because of this I added a low priority label.

**Comment by Taxxor90** [comment]
Implemented "Global time" toggle button.
![CX_globaltime](https://user-images.githubusercontent.com/45570250/124316942-abce9b00-db76-11eb-9a8d-fd5321812632.png)

Active by default, it uses the same capture time for all processes just as before. 

Unchecked, the capture time will be set automatically for each process according to the last capture time used for that process that wasn't a global time. As default, every process has "null" as it's specific capture time so at first the time will be the same as the global time.

Specific capture times for processes are only saved when the toggle is off while doing a benchmark. 
That way you can also use the global time(toggle on) for all benchmarks without overwriting the last specific time.
