### ISSUE TITLE
Adding lines in graphes triggered by MouseOver on threshold bar charts

### ISSUE THREAD

**Issue by DevTechProfile** [CXWorld/CapFrameX#98]
The option of adding a line or multiple lines on the frametime graph and L-shape graph for common fps frametimes (33.3ms, 16.6ms, 8.3ms etc) to more easily see the difference between desired frametimes and actual results on the graph itself. Would also make comparisons between setups a bit easier at a glance with stuttery setups as they can be quite "noisy" frametime graphs.

**Comment by Taxxor90** [comment]
Discarded
